// This file is auto generated by starling.js. DO NOT EDIT.
/* eslint-disable */

export const LOCALES_INDICES = {
  "ar": 0,
  "cs-CZ": 1,
  "de": 2,
  "en": 3,
  "es": 4,
  "fr": 5,
  "id": 6,
  "it": 7,
  "ja": 8,
  "ko": 9,
  "ms": 10,
  "pl-PL": 11,
  "pt-BR": 12,
  "pt": 12,
  "ru": 13,
  "sv-SE": 14,
  "th": 15,
  "tr": 16,
  "vi": 17,
  "zh": 18
};
