// This file is auto generated by starling.js. DO NOT EDIT.
/* eslint-disable */
import type { LocalizedMessage } from './utils';
export { LOCALES_INDICES } from './constants';

export { resolveMessage, isSupportedLocale, LocalizedMessage, Locale } from './utils';

// 翻译文案截止 0.4.3 版本 minified 后的体积只有 16KB (7KB gzipped)，并且支持 tree-shaking。
// 因此建议直接引入，无需动态加载，避免动态加载额外的网络和重渲染开销。
// The translations are only 16KB (7KB gzipped) minified till v0.4.3, and are tree-shakable.
// Therefore, it is recommended to directly import them instead of dynamically loading them.

export const badgeMessages = {
  new: ["جديد","Nové","Neu","New","Novedad","Nouveau","Baru","Novità","NEW","신규","Baharu","Nowe","Novidade","Новинка","Ny","ใหม่","Yeni","Mới","新增"] as LocalizedMessage<never>,
};

export const calendarMessages = {
  month: ["الشهر","Měsíc","Monat","Month","Mes","Mois","Bulan","Mese","月","월","Bulan","Miesiąc","Mês","Месяц","Månad","เดือน","Ay","Tháng","月"] as LocalizedMessage<never>,
  today: ["اليوم","Dnes","Heute","Today","Hoy","Aujourd'hui","Hari ini","Oggi","今日","오늘","Hari ini","Dzisiaj","Hoje","Сегодня","I dag","วันนี้","Bugün","Hôm nay","今天"] as LocalizedMessage<never>,
  year: ["السنة","Rok","Jahr","Year","Año","Année","Tahun","Anno","年","연도","Tahun","Rok","Ano","Год","År","ปี","Yıl","Năm","年"] as LocalizedMessage<never>,
};

export const commonMessages = {
  apply: ["تطبيق","Použít","Anwenden","Apply","Aplicar","Appliquer","Terapkan","Applica","適用","적용","Gunakan","Zastosuj","Aplicar","Применить","Använd","ปรับใช้","Uygula","Áp dụng","应用"] as LocalizedMessage<never>,
  back: ["العودة","Zpět","Zurück","Back","Atrás","Retour","Kembali","Indietro","戻る","뒤로","Kembali","Wstecz","Voltar","Назад","Tillbaka","ย้อนกลับ","Geri","Quay lại","返回"] as LocalizedMessage<never>,
  cancel: ["إلغاء","Zrušit","Abbrechen","Cancel","Cancelar","Annuler","Batalkan","Annulla","キャンセル","취소","Batal","Anuluj","Cancelar","Отмена","Avbryt","ยกเลิก","İptal Et","Hủy","取消"] as LocalizedMessage<never>,
  confirm: ["تأكيد","Potvrdit","Bestätigen","Confirm","Confirmar","Confirmer","Konfirmasi","Conferma","確認","확인","Sahkan","Potwierdź","Confirmar","Подтвердить","Bekräfta","ยืนยัน","Onayla","Xác nhận","确认"] as LocalizedMessage<never>,
  empty: ["لا توجد بيانات","Žádná data","Keine Daten","No Data","No hay datos","Aucune donnée","Tidak Ada Data","Nessun dato","データがありません","데이터 없음","Tiada data","Brak danych","Sem dados","Нет данных","Inga data","ไม่มีข้อมูล","Veri Yok","Không có dữ liệu","暂无数据"] as LocalizedMessage<never>,
  learnMore: ["معرفة المزيد","Další informace","Mehr erfahren","Learn more","Más información","En savoir plus","Pelajari selengkapnya","Maggiori informazioni","詳細を見る","자세히 알아보기","Ketahui lebih lanjut","Dowiedz się więcej","Saiba mais","Подробнее","Läs mer","เรียนรู้เพิ่มเติม","Daha fazla bilgi edinin","Tìm hiểu thêm","了解更多"] as LocalizedMessage<never>,
  next: ["التالي","Další","Weiter","Next","Siguiente","Suivant","Berikutnya","Avanti","次へ","다음","Seterusnya","Dalej","Avançar","Далее","Nästa","ถัดไป","Sonraki","Tiếp","下一步"] as LocalizedMessage<never>,
  placeholder: ["يرجى الإدخال","Zadejte","Bitte eingeben","Please enter","Introduce","Merci de saisir","Masukkan","Inserire","入力してください","입력하세요","Sila masukkan","Wprowadź","Insira","Введите","Ange","โปรดป้อน","Lütfen girin","Vui lòng nhập","请输入"] as LocalizedMessage<never>,
  loadFail: ["فشل التحميل","Chyba při načítání","Laden fehlgeschlagen","Failure loading","Error en la carga","Échec de chargement","Gagal memuat","Caricamento non riuscito","読み込みができませんでした","로딩 실패","Gagal memuatkan","Nie udało się załadować","Erro ao carregar","Сбой загрузки","Fel vid inläsning","โหลดไม่สำเร็จ","Yükleme başarısız","Không tải được","加载失败"] as LocalizedMessage<never>,
};

export const datePickerMessages = {
  end: ["تاريخ الانتهاء","Datum ukončení","Enddatum","End Date","Fecha y hora de finalización","Date de fin","Tanggal Selesai","Data di fine","終了日","종료일","Masa tamat","Data zakończenia","Data de término","Дата окончания","Slutdatum","เวลาสิ้นสุด","Bitiş saati","Ngày kết thúc","结束日期"] as LocalizedMessage<never>,
  lastNDays: ["آخر {days} من الأيام","Posledních {days} dnů","Letzte {days} Tage","Last {days} days","Últimos {days} días","{days} derniers jours","{days} hari terakhir","Ultimi {days} giorni","過去{days}日間","지난 {days}일","{days} hari yang lalu","Ostatnie {days} dni","Últimos {days} dias","За последние {days} дн.","Senaste {days} dagarna","{days} วันที่ผ่านมา","Son {days} gün","{days} ngày qua","过去 {days} 天"] as LocalizedMessage<{ days: string | number }>,
  lastNMonths: ["آخر {months} من الأشهر","Posledních měsíců: {months}","Letzte {months} Monate","Last {months} months","Últimos {months} meses","{months} derniers mois","{months} bulan terakhir","Ultimi {months} mesi","過去{months}ヶ月","지난 {months}개월","{months} bulan terakhir","Ostatnie {months} mies.","Últimos {months} meses","Последние {months} мес.","Senaste {months} månaderna","{months} เดือนที่ผ่านมา","Son {months} ay","{months} tháng qua","过去 {months} 个月"] as LocalizedMessage<{ months: string | number }>,
  placeholder: ["حدِّد التاريخ","Vybrat datum","Datum auswählen","Select date","Selecciona una fecha","Sélectionner la date","Pilih tanggal","Seleziona data","日付を選択","날짜 선택","Pilih tarikh","Wybierz datę","Selecionar data","Выберите дату","Välj datum","เลือกวันที่","Tarih seçin","Chọn ngày","选择日期"] as LocalizedMessage<never>,
  start: ["تاريخ البدء","Datum zahájení","Startdatum","Start Date","Fecha y hora de inicio","Date de début","Tanggal Mulai","Data di inizio","開始日","시작일","Masa mula","Data rozpoczęcia","Data de início","Дата начала","Startdatum","เวลาเริ่มต้น","Başlangıç saati","Ngày bắt đầu","开始日期"] as LocalizedMessage<never>,
  timezoneTip: ["تَستنِد هذه المنطقة الزمنية إلى إعدادات حساب الإعلانات الخاص بك.","Toto časové pásmo je nastaveno podle vašeho nastavení reklamního účtu.","Diese Zeitzone basiert auf den Einstellungen deines Anzeigenkontos.","This time zone is based on your ad account settings.","Esta zona horaria se basa en la configuración de tu cuenta publicitaria.","Ce fuseau horaire est basé sur les paramètres de votre compte publicitaire.","Zona waktu ini didasarkan pada pengaturan akun iklan Anda.","Questo fuso orario si basa sulle impostazioni del tuo account pubblicitario.","このタイムゾーンは広告アカウント設定に基づいています。","이 시간대는 광고 계정 설정을 기반으로 합니다.","Zon waktu ini adalah berdasarkan tetapan akaun iklan anda.","Ta strefa czasowa jest oparta na ustawieniach Twojego konta reklamowego.","Este fuso horário se baseia nas configurações da conta de anúncios.","Часовой пояс установлен на основе настроек рекламного аккаунта.","Tidszonen baseras på inställningarna i ditt annonskonto.","เขตเวลานี้เป็นไปตามการตั้งค่าบัญชีโฆษณาของคุณ","Saat dilimi, reklam hesabı ayarlarınıza bağlı olarak belirlenir.","Múi giờ này lấy theo cài đặt tài khoản quảng cáo của bạn.","此时区基于你的广告账户设置。"] as LocalizedMessage<never>,
};

export const dateTimePickerMessages = {
  end: ["تاريخ الانتهاء ووقته","Datum a čas ukončení","Enddatum und -zeit","End date and time","Fecha y hora de finalización","Date et heure de fin","Tanggal dan waktu selesai","Data e ora di fine","終了日時","종료 날짜 및 시간","Tarikh dan masa tamat","Data i czas zakończenia","Data e hora de término","Дата и время окончания","Slutdatum och sluttid","วันที่และเวลาสิ้นสุด","Bitiş tarihi ve saati","Ngày và giờ kết thúc","结束日期和时间"] as LocalizedMessage<never>,
  placeholder: ["تحديد التاريخ والوقت","Vyberte datum a čas","Datum und Uhrzeit auswählen","Select date and time","Selecciona una fecha y hora","Sélectionner une date et une heure","Pilih tanggal dan waktu","Seleziona data e ora","日時を選択してください","날짜 및 시간 선택","Pilih tarikh dan masa","Wybierz datę i godzinę","Selecionar data e hora","Выберите дату и время","Välj datum och tid","เลือกวันที่และเวลา","Tarih ve saat seçin","Chọn ngày và giờ","选择日期和时间"] as LocalizedMessage<never>,
  start: ["تاريخ البدء ووقته","Datum a čas zahájení","Startdatum und -zeit","Start date and time","Fecha y hora de inicio","Date et heure de début","Tanggal dan waktu mulai","Data e ora di inizio","開始日時","시작 날짜 및 시간","Tarikh dan masa mula","Data i czas rozpoczęcia","Data e hora de início","Дата и время начала","Startdatum och starttid","วันที่และเวลาเริ่มต้น","Başlangıç tarihi ve saati","Ngày và giờ bắt đầu","开始日期和时间"] as LocalizedMessage<never>,
};

export const dateMessages = {
  timezone: ["المنطقة الزمنية","Časové pásmo","Zeitzone","Timezone","Zona horaria","Fuseau horaire","Zona waktu","Fuso orario","タイムゾーン","시간대","Zon Waktu","Strefa czasowa","Fuso horário","Часовой пояс","Tidszon","เขตเวลา","Saat dilimi","Múi giờ","时区"] as LocalizedMessage<never>,
  utcTooltip: ["يعتمد عرض الإعلان على المنطقة الزمنية لحسابك المسجّل","Doručování reklam se řídí časovým pásmem vašeho registrovaného účtu.","Die Anzeigenauslieferung basiert auf der für dein Konto registrierten Zeitzone","Ad delivery is based on your registered account timezone","La publicación de anuncios se basa en la zona horaria en la que se ha registrado tu cuenta.","La diffusion d'annonces est basée sur le fuseau horaire enregistré pour ton compte","Penayangan iklan didasarkan pada zona waktu akun Anda","La pubblicazione degli annunci si basa sul fuso orario dell’account registrato","広告配信は登録されたアカウントのタイムゾーンに基づいています","광고 게재는 등록된 계정 시간대를 기반으로 합니다","Penyampaian iklan adalah berdasarkan zon waktu akaun berdaftar anda","Wyświetlanie reklam jest oparte na strefie czasowej zarejestrowanego konta","A veiculação do anúncio se baseia no fuso horário da conta registrada","Показ рекламы основан на часовом поясе, указанном в аккаунте","Annonsvisning baseras på ditt registrerade kontos tidszon","การนำเสนอโฆษณาจะเป็นไปตามเขตเวลาที่บัญชีของคุณลงทะเบียนไว้","Reklam sunumu, kayıtlı hesabınızın saat dilimine bağlıdır","Hoạt động phân phối quảng cáo dựa trên múi giờ của tài khoản mà bạn đã đăng ký","广告基于你注册账号时选择的时区进行投放"] as LocalizedMessage<never>,
};

export const formMessages = {
  optional: ["اختياري","Volitelné","Optional","Optional","Opcional","Facultatif","Opsional","Facoltativo","任意","선택 사항","Pilihan","Opcjonalnie","Opcional","Необязательно","Valfritt","ไม่บังคับ","İsteğe bağlı","Không bắt buộc","选填"] as LocalizedMessage<never>,
  required: ["مطلوب","Povinné","Erforderlich","Required","Obligatorio","Obligatoire","Wajib diisi","Obbligatorio","必須","필수 입력 항목","Diperlukan","Wymagane","Obrigatório","Обязательно","Obligatoriskt","ต้องระบุ","Gerekli","Bắt buộc","必填"] as LocalizedMessage<never>,
};

export const inputNumberMessages = {
  placeholder: ["أدخِل الرقم","Zadat číslo","Zahl eingeben","Enter number","Introduce un número","Saisir un nombre","Masukkan angka","Inserisci numero","番号を入力","숫자 입력","Masukkan nombor","Wpisz liczbę","Digite o número","Введите число","Ange nummer","ป้อนตัวเลข","Sayı girin","Nhập số","输入数字"] as LocalizedMessage<never>,
};

export const inputSelectorMessages = {
  placeholder: ["حدِّد","Vybrat","Auswählen","Select","Selecciona","Sélectionner","Pilih","Seleziona","選択してください","선택","Pilih","Wybierz","Selecionar","Выберите","Välj","เลือก","Seçin","Chọn","选择"] as LocalizedMessage<never>,
};

export const inputMessages = {
  placeholder: ["أدخِل النص","Zadat text","Text eingeben","Enter text","Introduce texto","Saisir du texte","Masukkan teks","Inserisci testo","テキストを入力","텍스트 입력","Masukkan teks","Wprowadź tekst","Inserir texto","Введите текст","Skriv text","ป้อนข้อความ","Metin girin","Nhập văn bản","输入文本"] as LocalizedMessage<never>,
};

export const paginationMessages = {
  go: ["انتقال","Přejít","Los","Go","Ir","Accéder","Buka","Vai","移動","이동","Pergi","Przejdź","Ir","Перейти","Gå till","ดำเนินการต่อ","Git","Đi","前往"] as LocalizedMessage<never>,
  page: ["الصفحة","stránka","Seite","page","página","page","halaman","pagina","ページ","페이지","halaman","strona","página","стр.","sida","หน้า","sayfa","trang","页"] as LocalizedMessage<never>,
  total: ["{total} إجمالي السجلات","Celkem záznamů: {total}","{total} Datensätze insgesamt","{total} Records in Total","{total} registros en total","{total} enregistrements au total","Total {total} Catatan","{total} record in totale","合計 {total} 件の記録","기록 총 {total}개","{total} rekod secara keseluruhan","Rekordy ogółem: {total}","{total} registros no total","Всего записей: {total}","Totalt {total} poster","รวมบันทึกทั้งหมด {total} รายการ","Toplam {total} Kayıt","Tổng cộng {total} bản ghi","共 {total} 条记录"] as LocalizedMessage<{ total: string | number }>,
};

export const searchMessages = {
  placeholder: ["ابحث","Vyhledat","Suche","Search","Busca","Rechercher","Cari","Cerca","検索","검색","Cari","Wyszukiwanie","Pesquisar","Поиск","Sök","ค้นหา","Arama","Tìm kiếm","搜索"] as LocalizedMessage<never>,
  result: ["نتائج البحث","Výsledky vyhledávání","Suchergebnisse","Search results","Resultados de búsqueda","Résultats de recherche","Hasil Pencarian","Risultati della ricerca","検索結果","검색 결과","Hasil Carian","Wyniki wyszukiwania","Resultados de pesquisa","Результаты поиска","Sökresultat","ผลการค้นหา","Arama sonuçları","Kết quả tìm kiếm","搜索结果"] as LocalizedMessage<never>,
};

export const selectMessages = {
  placeholder: ["يرجى التحديد","Vyberte prosím","Bitte auswählen","Please select","Selecciona","Veuillez effectuer une sélection","Pilih","Selezionare","選択してください","선택하세요","Sila pilih","Wybierz","Selecione","Выберите","Välj","โปรดเลือก","Lütfen seçin","Vui lòng chọn","请选择"] as LocalizedMessage<never>,
  selectAll: ["حدد الكل","Vybrat vše","Alle auswählen","Select all","Seleccionar todo","Sélectionner tout","Pilih semua","Seleziona tutto","すべてを選択","모두 선택","Pilih semua","Wybierz wszystko","Selecionar tudo","Выбрать все","Välj alla","เลือกทั้งหมด","Tümünü seç","Chọn tất cả","全选"] as LocalizedMessage<never>,
};

export const timePickerMessages = {
  endPlaceholder: ["وقت الانتهاء","Čas ukončení","Endzeit","End time","Hora de finalización","Heure de fin","Waktu selesai","Ora di fine","終了時間","종료 시간","Masa tamat","Czas zakończenia","Hora de fim","Время окончания","Sluttid","เวลาสิ้นสุด","Bitiş zamanı","Thời gian kết thúc","结束时间"] as LocalizedMessage<never>,
  placeholder: ["حدِّد الوقت","Vybrat čas","Uhrzeit auswählen","Select time","Selecciona una hora","Sélectionner l'heure","Pilih waktu","Seleziona ora","時間を選択","시간 선택","Pilih masa","Wybierz czas","Selecionar hora","Выберите время","Välj tid","เลือกเวลา","Saat seçin","Chọn thời gian","选择时间"] as LocalizedMessage<never>,
  startPlaceholder: ["وقت البدء","Čas zahájení","Startzeit","Start time","Hora de inicio","Heure de début","Waktu mulai","Ora di inizio","開始時間","시작 시간","Masa mula","Czas rozpoczęcia","Hora de início","Время начала","Starttid","เวลาเริ่มต้น","Başlangıç zamanı","Thời gian bắt đầu","开始时间"] as LocalizedMessage<never>,
};

export const uploadMessages = {
  button: ["تحميل","Nahrát","Hochladen","Upload","Cargar","Téléverser","Unggah","Carica","アップロード","업로드","Muat naik","Prześlij","Carregar","Загрузить","Ladda upp","อัปโหลด","Yükle","Tải lên","上传"] as LocalizedMessage<never>,
  click: ["انقر للتحميل","je nahrajte kliknutím.","zum Hochladen klicken","click to upload","haz clic para cargarlos","cliquez pour les téléverser","klik untuk mengunggah","fai clic per caricarli","クリックしてアップロード","클릭하여 업로드하세요","klik untuk memuat naik","kliknij, aby przesłać","clique para fazer upload","нажмите для загрузки","klicka för att ladda upp","คลิกเพื่ออัปโหลด","yüklemek için tıklayın","nhấp để tải lên","点击上传"] as LocalizedMessage<never>,
  drop: ["أفلِت الملفات هنا، أو","Přetáhněte soubory sem nebo","Dateien hier ablegen oder","Drop files here, or","Suelta los archivos aquí o","Déposez des fichiers ici ou","Taruh file di sini atau","Trascina i file qui o","ここにファイルをドロップするか","여기에 파일을 가져다 놓거나","Lepaskan fail di sini atau","Upuść pliki tutaj lub","Solte os arquivos aqui ou","Перетащите файлы сюда или","Släpp filer hit eller","วางไฟล์ที่นี่หรือ","Dosyaları buraya bırakın veya","Thả tệp vào đây, hoặc","将文件拖放到此处，或者"] as LocalizedMessage<never>,
  exceededMaxLimit: ["يمكنك تحميل حتى {num_max_files} من الملفات.","Můžete nahrát až {num_max_files} soubory(ů).","Du kannst bis zu {num_max_files} Dateien hochladen.","You can upload up to {num_max_files} files.","Puedes subir hasta {num_max_files} archivos.","Tu peux importer jusqu'à {num_max_files} fichiers.","Anda dapat mengunggah maksimum {num_max_files} file.","Puoi caricare fino a {num_max_files} file.","最大{num_max_files}件までファイルをアップロードできます。","파일은 {num_max_files}개까지 업로드할 수 있습니다.","Anda boleh memuat naik hingga {num_max_files} fail.","Maksymalna liczba plików do przesłania: {num_max_files}.","Você pode carregar até {num_max_files} arquivos.","Максимальное количество файлов для загрузки: {num_max_files}.","Du kan överföra upp till {num_max_files} filer.","คุณสามารถอัปโหลดได้สูงสุด {num_max_files} ไฟล์","En fazla {num_max_files} dosya yükleyebilirsiniz.","Bạn có thể tải lên tối đa {num_max_files} tệp.","你最多可以上传 {num_max_files} 个文件。"] as LocalizedMessage<{ num_max_files: string | number }>,
};

