/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'tiktok-display': ['TikTok Sans Display', 'sans-serif'],
        'tiktok-text': ['TikTok Sans Text', 'sans-serif'],
        'tiktok': ['TikTok Sans Text', 'sans-serif'], // Generic TikTok Sans maps to Text
      },
      colors: {
        // Primary Colors
        'ks-primary-surface': '#ffffff',
        'ks-primary-surface1': '#f2fdfc',
        'ks-primary-surface2': '#e8fbf9',
        'ks-primary-surface3': '#d7f2f0',
        'ks-primary-fill': '#009995',
        'ks-primary-fillLow': '#9ee1dd',
        'ks-primary-onSurface': '#017976',
        'ks-primary-onFill': '#ffffff',
        'ks-primary-onFillLow': '#002c2b',
        // Neutral Colors
        'ks-neutral-surface': '#ffffff',
        'ks-neutral-surface1': '#F8F8F9',
        'ks-neutral-surface2': '#F1F2F2',
        'ks-neutral-surface3': '#ECECED',
        'ks-neutral-surface4': '#D3D4D5',
        'ks-neutral-surface5': '#B9BBBC',
        'ks-neutral-onSurface': '#6D6E70',
        'ks-neutral-onSurface2': '#4F5052',
        'ks-neutral-onSurface3': '#262627',
        'ks-neutral-onSurface4': '#121415',
        'ks-neutral-highOnSurface': '#121415',
        'ks-neutral-fill': '#87898B',
        'ks-neutral-fillLow': '#D3D4D5',
        'ks-neutral-fillHigh': '#262627',
        'ks-neutral-onFill': '#ffffff',
        'ks-neutral-onFillLow': '#262627',
        'ks-neutral-transparentFill': 'rgba(18, 20, 21, 0)',
      },
      spacing: {
        'ks-0': '0px',
        'ks-1': '4px',
        'ks-2': '8px',
        'ks-3': '12px',
        'ks-4': '16px',
        'ks-5': '20px',
        'ks-6': '24px',
        'ks-8': '32px',
        'ks-9': '36px',
        'ks-10': '40px',
        'ks-12': '48px',
        'ks-14': '56px',
        'ks-16': '64px',
        'ks-18': '72px',
        'ks-20': '80px',
        'ks-22': '88px',
        'ks-24': '96px',
        'ks-0-5': '2px',
        'ks-100': '4px',
        'ks-200': '8px',
        'ks-2-5': '10px',
        'ks-300': '12px',
        'ks-400': '16px',
        'ks-600': '24px',
        'ks-1000': '40px',
      },
      borderRadius: {
        'ks-sm': '2px',
        'ks-md': '4px',
        'ks-lg': '6px',
        'ks-xl': '8px',
        'ks-full': '9999px',
      },
    },
  },
  plugins: [],
}
