'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsAnchor as KsAnchorElement, defineCustomElement as defineKsAnchor } from "@fe-infra/keystone/dist/components/ks-anchor.js";
import React from 'react';

type KsAnchorSlots = NonNullable<unknown>;
type KsAnchorEvents = { onAnchorItemClick: EventName<string> };
export type KsAnchorProps = ComponentProps<KsAnchorElement, KsAnchorEvents, KsAnchorSlots>;

const KsAnchor: StencilReactComponent<KsAnchorElement, KsAnchorEvents, KsAnchorSlots> = /*@__PURE__*/ createComponent<KsAnchorElement, KsAnchorEvents, KsAnchorSlots>({
    tagName: 'ks-anchor',
    elementClass: KsAnchorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onAnchorItemClick: 'ksAnchorItemClick' } as KsAnchorEvents,
    slots: {} as KsAnchorSlots,
    displayName: 'KsAnchor',
    defineCustomElement: defineKsAnchor,
    tagNameTransform: true
});

export default KsAnchor;
