'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type DropdownMenuItem } from "@fe-infra/keystone";
import { KsAssetTile as KsAssetTileElement, defineCustomElement as defineKsAssetTile } from "@fe-infra/keystone/dist/components/ks-asset-tile.js";
import React from 'react';

type KsAssetTileSlots = {
    /**
     * Slot for a custom icon, displayed if `image` prop is not set and the tile is not in a 'block' state.
     */
    icon: string,
    /**
     * Slot for a custom media player or content, displayed when `playing` is true and the tile is not in a 'block' state.
     */
    player: string,
    /**
     * Slot for custom content to be displayed inside the tooltip when the tile has a status (e.g., 'error', 'pending', 'warning').
     */
    statusContent: string,
    /**
     * Slot for custom assetTileContent area
     */
    contentWrapper: string
};
type KsAssetTileEvents = {
    onChange: EventName<boolean>,
    onAction: EventName<string | DropdownMenuItem>
};
export type KsAssetTileProps = ComponentProps<KsAssetTileElement, KsAssetTileEvents, KsAssetTileSlots>;

const KsAssetTile: StencilReactComponent<KsAssetTileElement, KsAssetTileEvents, KsAssetTileSlots> = /*@__PURE__*/ createComponent<KsAssetTileElement, KsAssetTileEvents, KsAssetTileSlots>({
    tagName: 'ks-asset-tile',
    elementClass: KsAssetTileElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onAction: 'ksAction'
    } as KsAssetTileEvents,
    slots: {
        icon: 'icon',
        player: 'player',
        statusContent: 'status-content',
        contentWrapper: 'content-wrapper'
    } as KsAssetTileSlots,
    displayName: 'KsAssetTile',
    defineCustomElement: defineKsAssetTile,
    tagNameTransform: true
});

export default KsAssetTile;
