'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsAvatarGroup as KsAvatarGroupElement, defineCustomElement as defineKsAvatarGroup } from "@fe-infra/keystone/dist/components/ks-avatar-group.js";
import React from 'react';

type KsAvatarGroupSlots = NonNullable<unknown>;
type KsAvatarGroupEvents = NonNullable<unknown>;
export type KsAvatarGroupProps = ComponentProps<KsAvatarGroupElement, KsAvatarGroupEvents, KsAvatarGroupSlots>;

const KsAvatarGroup: StencilReactComponent<KsAvatarGroupElement, KsAvatarGroupEvents, KsAvatarGroupSlots> = /*@__PURE__*/ createComponent<KsAvatarGroupElement, KsAvatarGroupEvents, KsAvatarGroupSlots>({
    tagName: 'ks-avatar-group',
    elementClass: KsAvatarGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsAvatarGroupEvents,
    slots: {} as KsAvatarGroupSlots,
    displayName: 'KsAvatarGroup',
    defineCustomElement: defineKsAvatarGroup,
    tagNameTransform: true
});

export default KsAvatarGroup;
