'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsAvatar as KsAvatarElement, defineCustomElement as defineKsAvatar } from "@fe-infra/keystone/dist/components/ks-avatar.js";
import React from 'react';

type KsAvatarSlots = {
    /**
     * Used to place elements on top of the avatar, often for badges or status indicators. only takes effect when size is lg
     */
    overlap: string
};
type KsAvatarEvents = NonNullable<unknown>;
export type KsAvatarProps = ComponentProps<KsAvatarElement, KsAvatarEvents, KsAvatarSlots>;

const KsAvatar: StencilReactComponent<KsAvatarElement, KsAvatarEvents, KsAvatarSlots> = /*@__PURE__*/ createComponent<KsAvatarElement, KsAvatarEvents, KsAvatarSlots>({
    tagName: 'ks-avatar',
    elementClass: KsAvatarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsAvatarEvents,
    slots: { overlap: 'overlap' } as KsAvatarSlots,
    displayName: 'KsAvatar',
    defineCustomElement: defineKsAvatar,
    tagNameTransform: true
});

export default KsAvatar;
