'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsBadge as KsBadgeElement, defineCustomElement as defineKsBadge } from "@fe-infra/keystone/dist/components/ks-badge.js";
import React from 'react';

type KsBadgeSlots = {
    /**
     * Custom content for the badge indicator itself (e.g., text or number). If not provided for `type="count"` or `type="content"`, default content based on props will be rendered.
     */
    sup: string
};
type KsBadgeEvents = NonNullable<unknown>;
export type KsBadgeProps = ComponentProps<KsBadgeElement, KsBadgeEvents, KsBadgeSlots>;

const KsBadge: StencilReactComponent<KsBadgeElement, KsBadgeEvents, KsBadgeSlots> = /*@__PURE__*/ createComponent<KsBadgeElement, KsBadgeEvents, KsBadgeSlots>({
    tagName: 'ks-badge',
    elementClass: KsBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsBadgeEvents,
    slots: { sup: 'sup' } as KsBadgeSlots,
    displayName: 'KsBadge',
    defineCustomElement: defineKsBadge,
    tagNameTransform: true
});

export default KsBadge;
