'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsBreadcrumb as KsBreadcrumbElement, defineCustomElement as defineKsBreadcrumb } from "@fe-infra/keystone/dist/components/ks-breadcrumb.js";
import React from 'react';

type KsBreadcrumbSlots = NonNullable<unknown>;
type KsBreadcrumbEvents = { onClickDropdownItem: EventName<string> };
export type KsBreadcrumbProps = ComponentProps<KsBreadcrumbElement, KsBreadcrumbEvents, KsBreadcrumbSlots>;

const KsBreadcrumb: StencilReactComponent<KsBreadcrumbElement, KsBreadcrumbEvents, KsBreadcrumbSlots> = /*@__PURE__*/ createComponent<KsBreadcrumbElement, KsBreadcrumbEvents, KsBreadcrumbSlots>({
    tagName: 'ks-breadcrumb',
    elementClass: KsBreadcrumbElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onClickDropdownItem: 'ksClickDropdownItem' } as KsBreadcrumbEvents,
    slots: {} as KsBreadcrumbSlots,
    displayName: 'KsBreadcrumb',
    defineCustomElement: defineKsBreadcrumb,
    tagNameTransform: true
});

export default KsBreadcrumb;
