'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsBulletinTile as KsBulletinTileElement, defineCustomElement as defineKsBulletinTile } from "@fe-infra/keystone/dist/components/ks-bulletin-tile.js";
import React from 'react';

type KsBulletinTileSlots = NonNullable<unknown>;
type KsBulletinTileEvents = {
    onButtonClick: EventName<{
        key: string | number;
        text: string;
        index: number;
    }>
};
export type KsBulletinTileProps = ComponentProps<KsBulletinTileElement, KsBulletinTileEvents, KsBulletinTileSlots>;

const KsBulletinTile: StencilReactComponent<KsBulletinTileElement, KsBulletinTileEvents, KsBulletinTileSlots> = /*@__PURE__*/ createComponent<KsBulletinTileElement, KsBulletinTileEvents, KsBulletinTileSlots>({
    tagName: 'ks-bulletin-tile',
    elementClass: KsBulletinTileElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onButtonClick: 'ksButtonClick' } as KsBulletinTileEvents,
    slots: {} as KsBulletinTileSlots,
    displayName: 'KsBulletinTile',
    defineCustomElement: defineKsBulletinTile,
    tagNameTransform: true
});

export default KsBulletinTile;
