'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsButtonGroupItem as KsButtonGroupItemElement, defineCustomElement as defineKsButtonGroupItem } from "@fe-infra/keystone/dist/components/ks-button-group-item.js";
import React from 'react';

type KsButtonGroupItemSlots = NonNullable<unknown>;
type KsButtonGroupItemEvents = NonNullable<unknown>;
export type KsButtonGroupItemProps = ComponentProps<KsButtonGroupItemElement, KsButtonGroupItemEvents, KsButtonGroupItemSlots>;

const KsButtonGroupItem: StencilReactComponent<KsButtonGroupItemElement, KsButtonGroupItemEvents, KsButtonGroupItemSlots> = /*@__PURE__*/ createComponent<KsButtonGroupItemElement, KsButtonGroupItemEvents, KsButtonGroupItemSlots>({
    tagName: 'ks-button-group-item',
    elementClass: KsButtonGroupItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsButtonGroupItemEvents,
    slots: {} as KsButtonGroupItemSlots,
    displayName: 'KsButtonGroupItem',
    defineCustomElement: defineKsButtonGroupItem,
    tagNameTransform: true
});

export default KsButtonGroupItem;
