'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsButton as KsButtonElement, defineCustomElement as defineKsButton } from "@fe-infra/keystone/dist/components/ks-button.js";
import React from 'react';

type KsButtonSlots = {
    /**
     * Custom content to display when the button is in a loading state. If not provided, a default loading spinner (`ks-icon-loading`) is shown.
     */
    loading: string
};
type KsButtonEvents = NonNullable<unknown>;
export type KsButtonProps = ComponentProps<KsButtonElement, KsButtonEvents, KsButtonSlots>;

const KsButton: StencilReactComponent<KsButtonElement, KsButtonEvents, KsButtonSlots> = /*@__PURE__*/ createComponent<KsButtonElement, KsButtonEvents, KsButtonSlots>({
    tagName: 'ks-button',
    elementClass: KsButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsButtonEvents,
    slots: { loading: 'loading' } as KsButtonSlots,
    displayName: 'KsButton',
    defineCustomElement: defineKsButton,
    tagNameTransform: true
});

export default KsButton;
