'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsButtonGroup as KsButtonGroupElement, defineCustomElement as defineKsButtonGroup } from "@fe-infra/keystone/dist/components/ks-button-group.js";
import React from 'react';

type KsButtonGroupSlots = NonNullable<unknown>;
type KsButtonGroupEvents = { onChange: EventName<string[]> };
export type KsButtonGroupProps = ComponentProps<KsButtonGroupElement, KsButtonGroupEvents, KsButtonGroupSlots>;

const KsButtonGroup: StencilReactComponent<KsButtonGroupElement, KsButtonGroupEvents, KsButtonGroupSlots> = /*@__PURE__*/ createComponent<KsButtonGroupElement, KsButtonGroupEvents, KsButtonGroupSlots>({
    tagName: 'ks-button-group',
    elementClass: KsButtonGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsButtonGroupEvents,
    slots: {} as KsButtonGroupSlots,
    displayName: 'KsButtonGroup',
    defineCustomElement: defineKsButtonGroup,
    tagNameTransform: true
});

export default KsButtonGroup;
