'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCarousel as KsCarouselElement, defineCustomElement as defineKsCarousel } from "@fe-infra/keystone/dist/components/ks-carousel.js";
import React from 'react';

type KsCarouselSlots = NonNullable<unknown>;
type KsCarouselEvents = NonNullable<unknown>;
export type KsCarouselProps = ComponentProps<KsCarouselElement, KsCarouselEvents, KsCarouselSlots>;

const KsCarousel: StencilReactComponent<KsCarouselElement, KsCarouselEvents, KsCarouselSlots> = /*@__PURE__*/ createComponent<KsCarouselElement, KsCarouselEvents, KsCarouselSlots>({
    tagName: 'ks-carousel',
    elementClass: KsCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsCarouselEvents,
    slots: {} as KsCarouselSlots,
    displayName: 'KsCarousel',
    defineCustomElement: defineKsCarousel,
    tagNameTransform: true
});

export default KsCarousel;
