'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCarouselItem as KsCarouselItemElement, defineCustomElement as defineKsCarouselItem } from "@fe-infra/keystone/dist/components/ks-carousel-item.js";
import React from 'react';

type KsCarouselItemSlots = NonNullable<unknown>;
type KsCarouselItemEvents = NonNullable<unknown>;
export type KsCarouselItemProps = ComponentProps<KsCarouselItemElement, KsCarouselItemEvents, KsCarouselItemSlots>;

const KsCarouselItem: StencilReactComponent<KsCarouselItemElement, KsCarouselItemEvents, KsCarouselItemSlots> = /*@__PURE__*/ createComponent<KsCarouselItemElement, KsCarouselItemEvents, KsCarouselItemSlots>({
    tagName: 'ks-carousel-item',
    elementClass: KsCarouselItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsCarouselItemEvents,
    slots: {} as KsCarouselItemSlots,
    displayName: 'KsCarouselItem',
    defineCustomElement: defineKsCarouselItem,
    tagNameTransform: true
});

export default KsCarouselItem;
