'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCalendar as KsCalendarElement, defineCustomElement as defineKsCalendar } from "@fe-infra/keystone/dist/components/ks-calendar.js";
import React from 'react';

type KsCalendarSlots = {
    /**
     * Allows customization of the calendar header area.
     */
    header: string
};
type KsCalendarEvents = {
    onMonthChange: EventName<{ start: Date; end: Date }>,
    onSelect: EventName<Date | { start: Date; end: Date }>
};
export type KsCalendarProps = ComponentProps<KsCalendarElement, KsCalendarEvents, KsCalendarSlots>;

const KsCalendar: StencilReactComponent<KsCalendarElement, KsCalendarEvents, KsCalendarSlots> = /*@__PURE__*/ createComponent<KsCalendarElement, KsCalendarEvents, KsCalendarSlots>({
    tagName: 'ks-calendar',
    elementClass: KsCalendarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onMonthChange: 'ksMonthChange',
        onSelect: 'ksSelect'
    } as KsCalendarEvents,
    slots: { header: 'header' } as KsCalendarSlots,
    displayName: 'KsCalendar',
    defineCustomElement: defineKsCalendar,
    tagNameTransform: true
});

export default KsCalendar;
