'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type CascaderItemValue } from "@fe-infra/keystone";
import { KsCascader as KsCascaderElement, defineCustomElement as defineKsCascader } from "@fe-infra/keystone/dist/components/ks-cascader.js";
import React from 'react';

type KsCascaderSlots = {
    /**
     * Slot for content at the top of the dropdown panel.
     */
    panelHeader: string,
    /**
     * Slot for content at the bottom of the dropdown panel.
     */
    panelFooter: string,
    /**
     * Slot for prefix content before the input display.
     */
    prefix: string,
    /**
     * Slot for a custom expansion indicator icon.
     */
    showIcon: string,
    /**
     * Slot for a custom clear icon.
     */
    closeIcon: string,
    /**
     * Slot for suffix content after the input display (overrides show-icon & close-icon).
     */
    suffix: string,
    /**
     * Slot for selected content.
     */
    selected: string
};
type KsCascaderEvents = {
    onChange: EventName<CascaderItemValue>,
    onVisibleChange: EventName<boolean>,
    onSearchChange: EventName<string>
};
export type KsCascaderProps = ComponentProps<KsCascaderElement, KsCascaderEvents, KsCascaderSlots>;

const KsCascader: StencilReactComponent<KsCascaderElement, KsCascaderEvents, KsCascaderSlots> = /*@__PURE__*/ createComponent<KsCascaderElement, KsCascaderEvents, KsCascaderSlots>({
    tagName: 'ks-cascader',
    elementClass: KsCascaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onVisibleChange: 'ksVisibleChange',
        onSearchChange: 'ksSearchChange'
    } as KsCascaderEvents,
    slots: {
        panelHeader: 'panel-header',
        panelFooter: 'panel-footer',
        prefix: 'prefix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        suffix: 'suffix',
        selected: 'selected'
    } as KsCascaderSlots,
    displayName: 'KsCascader',
    defineCustomElement: defineKsCascader,
    tagNameTransform: true
});

export default KsCascader;
