'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCard as KsCardElement, defineCustomElement as defineKsCard } from "@fe-infra/keystone/dist/components/ks-card.js";
import React from 'react';

type KsCardSlots = {
    /**
     * The slot for the card's title section. Overrides the `title` prop if provided.
     */
    title: string,
    /**
     * The slot for extra content in the card's header, usually on the right.
     */
    extra: string
};
type KsCardEvents = NonNullable<unknown>;
export type KsCardProps = ComponentProps<KsCardElement, KsCardEvents, KsCardSlots>;

const KsCard: StencilReactComponent<KsCardElement, KsCardEvents, KsCardSlots> = /*@__PURE__*/ createComponent<KsCardElement, KsCardEvents, KsCardSlots>({
    tagName: 'ks-card',
    elementClass: KsCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsCardEvents,
    slots: {
        title: 'title',
        extra: 'extra'
    } as KsCardSlots,
    displayName: 'KsCard',
    defineCustomElement: defineKsCard,
    tagNameTransform: true
});

export default KsCard;
