'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCascaderColumns as KsCascaderColumnsElement, defineCustomElement as defineKsCascaderColumns } from "@fe-infra/keystone/dist/components/ks-cascader-columns.js";
import React from 'react';

type KsCascaderColumnsSlots = NonNullable<unknown>;
type KsCascaderColumnsEvents = NonNullable<unknown>;
export type KsCascaderColumnsProps = ComponentProps<KsCascaderColumnsElement, KsCascaderColumnsEvents, KsCascaderColumnsSlots>;

const KsCascaderColumns: StencilReactComponent<KsCascaderColumnsElement, KsCascaderColumnsEvents, KsCascaderColumnsSlots> = /*@__PURE__*/ createComponent<KsCascaderColumnsElement, KsCascaderColumnsEvents, KsCascaderColumnsSlots>({
    tagName: 'ks-cascader-columns',
    elementClass: KsCascaderColumnsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsCascaderColumnsEvents,
    slots: {} as KsCascaderColumnsSlots,
    displayName: 'KsCascaderColumns',
    defineCustomElement: defineKsCascaderColumns,
    tagNameTransform: true
});

export default KsCascaderColumns;
