'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsChip as KsChipElement, defineCustomElement as defineKsChip } from "@fe-infra/keystone/dist/components/ks-chip.js";
import React from 'react';

type KsChipSlots = {
    /**
     * The slot for the prefix content.
     */
    prefix: string
};
type KsChipEvents = { onChange: EventName<boolean> };
export type KsChipProps = ComponentProps<KsChipElement, KsChipEvents, KsChipSlots>;

const KsChip: StencilReactComponent<KsChipElement, KsChipEvents, KsChipSlots> = /*@__PURE__*/ createComponent<KsChipElement, KsChipEvents, KsChipSlots>({
    tagName: 'ks-chip',
    elementClass: KsChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsChipEvents,
    slots: { prefix: 'prefix' } as KsChipSlots,
    displayName: 'KsChip',
    defineCustomElement: defineKsChip,
    tagNameTransform: true
});

export default KsChip;
