'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCheckbox as KsCheckboxElement, defineCustomElement as defineKsCheckbox } from "@fe-infra/keystone/dist/components/ks-checkbox.js";
import React from 'react';

type KsCheckboxSlots = {
    /**
     * The slot for a custom structure of the entire label area, including the checkbox visual and text.
     */
    label: string,
    /**
     * The slot for providing descriptive text for the checkbox.
     */
    description: string,
    /**
     * The slot for the suffix.
     */
    suffix: string
};
type KsCheckboxEvents = { onChange: EventName<boolean> };
export type KsCheckboxProps = ComponentProps<KsCheckboxElement, KsCheckboxEvents, KsCheckboxSlots>;

const KsCheckbox: StencilReactComponent<KsCheckboxElement, KsCheckboxEvents, KsCheckboxSlots> = /*@__PURE__*/ createComponent<KsCheckboxElement, KsCheckboxEvents, KsCheckboxSlots>({
    tagName: 'ks-checkbox',
    elementClass: KsCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsCheckboxEvents,
    slots: {
        label: 'label',
        description: 'description',
        suffix: 'suffix'
    } as KsCheckboxSlots,
    displayName: 'KsCheckbox',
    defineCustomElement: defineKsCheckbox,
    tagNameTransform: true
});

export default KsCheckbox;
