'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type CheckboxGroupValue } from "@fe-infra/keystone";
import { KsCheckboxGroup as KsCheckboxGroupElement, defineCustomElement as defineKsCheckboxGroup } from "@fe-infra/keystone/dist/components/ks-checkbox-group.js";
import React from 'react';

type KsCheckboxGroupSlots = NonNullable<unknown>;
type KsCheckboxGroupEvents = { onChange: EventName<CheckboxGroupValue> };
export type KsCheckboxGroupProps = ComponentProps<KsCheckboxGroupElement, KsCheckboxGroupEvents, KsCheckboxGroupSlots>;

const KsCheckboxGroup: StencilReactComponent<KsCheckboxGroupElement, KsCheckboxGroupEvents, KsCheckboxGroupSlots> = /*@__PURE__*/ createComponent<KsCheckboxGroupElement, KsCheckboxGroupEvents, KsCheckboxGroupSlots>({
    tagName: 'ks-checkbox-group',
    elementClass: KsCheckboxGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsCheckboxGroupEvents,
    slots: {} as KsCheckboxGroupSlots,
    displayName: 'KsCheckboxGroup',
    defineCustomElement: defineKsCheckboxGroup,
    tagNameTransform: true
});

export default KsCheckboxGroup;
