'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsConfigProvider as KsConfigProviderElement, defineCustomElement as defineKsConfigProvider } from "@fe-infra/keystone/dist/components/ks-config-provider.js";
import React from 'react';

type KsConfigProviderSlots = NonNullable<unknown>;
type KsConfigProviderEvents = NonNullable<unknown>;
export type KsConfigProviderProps = ComponentProps<KsConfigProviderElement, KsConfigProviderEvents, KsConfigProviderSlots>;

const KsConfigProvider: StencilReactComponent<KsConfigProviderElement, KsConfigProviderEvents, KsConfigProviderSlots> = /*@__PURE__*/ createComponent<KsConfigProviderElement, KsConfigProviderEvents, KsConfigProviderSlots>({
    tagName: 'ks-config-provider',
    elementClass: KsConfigProviderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsConfigProviderEvents,
    slots: {} as KsConfigProviderSlots,
    displayName: 'KsConfigProvider',
    defineCustomElement: defineKsConfigProvider,
    tagNameTransform: true
});

export default KsConfigProvider;
