'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCollapseTransition as KsCollapseTransitionElement, defineCustomElement as defineKsCollapseTransition } from "@fe-infra/keystone/dist/components/ks-collapse-transition.js";
import React from 'react';

type KsCollapseTransitionSlots = NonNullable<unknown>;
type KsCollapseTransitionEvents = NonNullable<unknown>;
export type KsCollapseTransitionProps = ComponentProps<KsCollapseTransitionElement, KsCollapseTransitionEvents, KsCollapseTransitionSlots>;

const KsCollapseTransition: StencilReactComponent<KsCollapseTransitionElement, KsCollapseTransitionEvents, KsCollapseTransitionSlots> = /*@__PURE__*/ createComponent<KsCollapseTransitionElement, KsCollapseTransitionEvents, KsCollapseTransitionSlots>({
    tagName: 'ks-collapse-transition',
    elementClass: KsCollapseTransitionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsCollapseTransitionEvents,
    slots: {} as KsCollapseTransitionSlots,
    displayName: 'KsCollapseTransition',
    defineCustomElement: defineKsCollapseTransition,
    tagNameTransform: true
});

export default KsCollapseTransition;
