'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsCrop as KsCropElement, defineCustomElement as defineKsCrop } from "@fe-infra/keystone/dist/components/ks-crop.js";
import React from 'react';

type KsCropSlots = NonNullable<unknown>;
type KsCropEvents = NonNullable<unknown>;
export type KsCropProps = ComponentProps<KsCropElement, KsCropEvents, KsCropSlots>;

const KsCrop: StencilReactComponent<KsCropElement, KsCropEvents, KsCropSlots> = /*@__PURE__*/ createComponent<KsCropElement, KsCropEvents, KsCropSlots>({
    tagName: 'ks-crop',
    elementClass: KsCropElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsCropEvents,
    slots: {} as KsCropSlots,
    displayName: 'KsCrop',
    defineCustomElement: defineKsCrop,
    tagNameTransform: true
});

export default KsCrop;
