'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsDatePicker as KsDatePickerElement, defineCustomElement as defineKsDatePicker } from "@fe-infra/keystone/dist/components/ks-date-picker.js";
import React from 'react';

type KsDatePickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date options.
     */
    preset: string,
    /**
     * Slot for footer content in the picker panel.
     */
    footer: string
};
type KsDatePickerEvents = {
    onChange: EventName<IDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsDatePickerProps = ComponentProps<KsDatePickerElement, KsDatePickerEvents, KsDatePickerSlots>;

const KsDatePicker: StencilReactComponent<KsDatePickerElement, KsDatePickerEvents, KsDatePickerSlots> = /*@__PURE__*/ createComponent<KsDatePickerElement, KsDatePickerEvents, KsDatePickerSlots>({
    tagName: 'ks-date-picker',
    elementClass: KsDatePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsDatePickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset',
        footer: 'footer'
    } as KsDatePickerSlots,
    displayName: 'KsDatePicker',
    defineCustomElement: defineKsDatePicker,
    tagNameTransform: true
});

export default KsDatePicker;
