'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsDateTimePanel as KsDateTimePanelElement, defineCustomElement as defineKsDateTimePanel } from "@fe-infra/keystone/dist/components/ks-date-time-panel.js";
import React from 'react';

type KsDateTimePanelSlots = {
    /**
     * preset slot
     */
    preset: string
};
type KsDateTimePanelEvents = {
    onDateChange: EventName<IDateValue>,
    onTimeChange: EventName<string>
};
export type KsDateTimePanelProps = ComponentProps<KsDateTimePanelElement, KsDateTimePanelEvents, KsDateTimePanelSlots>;

const KsDateTimePanel: StencilReactComponent<KsDateTimePanelElement, KsDateTimePanelEvents, KsDateTimePanelSlots> = /*@__PURE__*/ createComponent<KsDateTimePanelElement, KsDateTimePanelEvents, KsDateTimePanelSlots>({
    tagName: 'ks-date-time-panel',
    elementClass: KsDateTimePanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDateChange: 'ksDateChange',
        onTimeChange: 'ksTimeChange'
    } as KsDateTimePanelEvents,
    slots: { preset: 'preset' } as KsDateTimePanelSlots,
    displayName: 'KsDateTimePanel',
    defineCustomElement: defineKsDateTimePanel,
    tagNameTransform: true
});

export default KsDateTimePanel;
