'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type ICompareValue } from "@fe-infra/keystone";
import { KsDateComparisonPicker as KsDateComparisonPickerElement, defineCustomElement as defineKsDateComparisonPicker } from "@fe-infra/keystone/dist/components/ks-date-comparison-picker.js";
import React from 'react';

type KsDateComparisonPickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for source preset options.
     */
    sourcePreset: string,
    /**
     * Slot for target preset options.
     */
    targetPreset: string
};
type KsDateComparisonPickerEvents = {
    onChange: EventName<ICompareValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsDateComparisonPickerProps = ComponentProps<KsDateComparisonPickerElement, KsDateComparisonPickerEvents, KsDateComparisonPickerSlots>;

const KsDateComparisonPicker: StencilReactComponent<KsDateComparisonPickerElement, KsDateComparisonPickerEvents, KsDateComparisonPickerSlots> = /*@__PURE__*/ createComponent<KsDateComparisonPickerElement, KsDateComparisonPickerEvents, KsDateComparisonPickerSlots>({
    tagName: 'ks-date-comparison-picker',
    elementClass: KsDateComparisonPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsDateComparisonPickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        sourcePreset: 'source-preset',
        targetPreset: 'target-preset'
    } as KsDateComparisonPickerSlots,
    displayName: 'KsDateComparisonPicker',
    defineCustomElement: defineKsDateComparisonPicker,
    tagNameTransform: true
});

export default KsDateComparisonPicker;
