'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsDateTimeRangePicker as KsDateTimeRangePickerElement, defineCustomElement as defineKsDateTimeRangePicker } from "@fe-infra/keystone/dist/components/ks-date-time-range-picker.js";
import React from 'react';

type KsDateTimeRangePickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date and time range options.
     */
    preset: string,
    /**
     * Slot for footer content in the picker panel.
     */
    footer: string
};
type KsDateTimeRangePickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>,
    onClear: EventName<void>
};
export type KsDateTimeRangePickerProps = ComponentProps<KsDateTimeRangePickerElement, KsDateTimeRangePickerEvents, KsDateTimeRangePickerSlots>;

const KsDateTimeRangePicker: StencilReactComponent<KsDateTimeRangePickerElement, KsDateTimeRangePickerEvents, KsDateTimeRangePickerSlots> = /*@__PURE__*/ createComponent<KsDateTimeRangePickerElement, KsDateTimeRangePickerEvents, KsDateTimeRangePickerSlots>({
    tagName: 'ks-date-time-range-picker',
    elementClass: KsDateTimeRangePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange',
        onClear: 'ksClear'
    } as KsDateTimeRangePickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset',
        footer: 'footer'
    } as KsDateTimeRangePickerSlots,
    displayName: 'KsDateTimeRangePicker',
    defineCustomElement: defineKsDateTimeRangePicker,
    tagNameTransform: true
});

export default KsDateTimeRangePicker;
