'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsDateTimeRangePanel as KsDateTimeRangePanelElement, defineCustomElement as defineKsDateTimeRangePanel } from "@fe-infra/keystone/dist/components/ks-date-time-range-panel.js";
import React from 'react';

type KsDateTimeRangePanelSlots = {
    /**
     * preset slot
     */
    preset: string
};
type KsDateTimeRangePanelEvents = {
    onChange: EventName<IDateValue[]>,
    onDateChange: EventName<IDateValue[]>,
    onTimeChange: EventName<string[]>
};
export type KsDateTimeRangePanelProps = ComponentProps<KsDateTimeRangePanelElement, KsDateTimeRangePanelEvents, KsDateTimeRangePanelSlots>;

const KsDateTimeRangePanel: StencilReactComponent<KsDateTimeRangePanelElement, KsDateTimeRangePanelEvents, KsDateTimeRangePanelSlots> = /*@__PURE__*/ createComponent<KsDateTimeRangePanelElement, KsDateTimeRangePanelEvents, KsDateTimeRangePanelSlots>({
    tagName: 'ks-date-time-range-panel',
    elementClass: KsDateTimeRangePanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onDateChange: 'ksDateChange',
        onTimeChange: 'ksTimeChange'
    } as KsDateTimeRangePanelEvents,
    slots: { preset: 'preset' } as KsDateTimeRangePanelSlots,
    displayName: 'KsDateTimeRangePanel',
    defineCustomElement: defineKsDateTimeRangePanel,
    tagNameTransform: true
});

export default KsDateTimeRangePanel;
