'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsDateRangePicker as KsDateRangePickerElement, defineCustomElement as defineKsDateRangePicker } from "@fe-infra/keystone/dist/components/ks-date-range-picker.js";
import React from 'react';

type KsDateRangePickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date range options.
     */
    preset: string,
    /**
     * Slot for footer content in the picker panel.
     */
    footer: string
};
type KsDateRangePickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>,
    onClear: EventName<void>
};
export type KsDateRangePickerProps = ComponentProps<KsDateRangePickerElement, KsDateRangePickerEvents, KsDateRangePickerSlots>;

const KsDateRangePicker: StencilReactComponent<KsDateRangePickerElement, KsDateRangePickerEvents, KsDateRangePickerSlots> = /*@__PURE__*/ createComponent<KsDateRangePickerElement, KsDateRangePickerEvents, KsDateRangePickerSlots>({
    tagName: 'ks-date-range-picker',
    elementClass: KsDateRangePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange',
        onClear: 'ksClear'
    } as KsDateRangePickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset',
        footer: 'footer'
    } as KsDateRangePickerSlots,
    displayName: 'KsDateRangePicker',
    defineCustomElement: defineKsDateRangePicker,
    tagNameTransform: true
});

export default KsDateRangePicker;
