'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsDateTimePicker as KsDateTimePickerElement, defineCustomElement as defineKsDateTimePicker } from "@fe-infra/keystone/dist/components/ks-date-time-picker.js";
import React from 'react';

type KsDateTimePickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date and time options.
     */
    preset: string,
    /**
     * Slot for footer content in the picker panel.
     */
    footer: string
};
type KsDateTimePickerEvents = {
    onChange: EventName<IDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsDateTimePickerProps = ComponentProps<KsDateTimePickerElement, KsDateTimePickerEvents, KsDateTimePickerSlots>;

const KsDateTimePicker: StencilReactComponent<KsDateTimePickerElement, KsDateTimePickerEvents, KsDateTimePickerSlots> = /*@__PURE__*/ createComponent<KsDateTimePickerElement, KsDateTimePickerEvents, KsDateTimePickerSlots>({
    tagName: 'ks-date-time-picker',
    elementClass: KsDateTimePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsDateTimePickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset',
        footer: 'footer'
    } as KsDateTimePickerSlots,
    displayName: 'KsDateTimePicker',
    defineCustomElement: defineKsDateTimePicker,
    tagNameTransform: true
});

export default KsDateTimePicker;
