'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsDivider as KsDividerElement, defineCustomElement as defineKsDivider } from "@fe-infra/keystone/dist/components/ks-divider.js";
import React from 'react';

type KsDividerSlots = NonNullable<unknown>;
type KsDividerEvents = NonNullable<unknown>;
export type KsDividerProps = ComponentProps<KsDividerElement, KsDividerEvents, KsDividerSlots>;

const KsDivider: StencilReactComponent<KsDividerElement, KsDividerEvents, KsDividerSlots> = /*@__PURE__*/ createComponent<KsDividerElement, KsDividerEvents, KsDividerSlots>({
    tagName: 'ks-divider',
    elementClass: KsDividerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsDividerEvents,
    slots: {} as KsDividerSlots,
    displayName: 'KsDivider',
    defineCustomElement: defineKsDivider,
    tagNameTransform: true
});

export default KsDivider;
