'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type DropdownMenuItem } from "@fe-infra/keystone";
import { KsDropdownMenu as KsDropdownMenuElement, defineCustomElement as defineKsDropdownMenu } from "@fe-infra/keystone/dist/components/ks-dropdown-menu.js";
import React from 'react';

type KsDropdownMenuSlots = {
    /**
     * Slot for custom header content within the dropdown panel.
     */
    header: string,
    /**
     * Slot for custom list header content within the dropdown panel.
     */
    listHeader: string,
    /**
     * Slot for the main custom content area within the dropdown panel.
     */
    content: string,
    /**
     * Slot for custom footer content within the dropdown panel.
     */
    footer: string,
    /**
     * Slot for content to display when the dropdown panel is empty.
     */
    empty: string,
    /**
     * Slot for content to display when the dropdown panel is load fail.
     */
    error: string,
    /**
     * Slot for cta button to display when the dropdown panel is load fail
     */
    loadFailCtas: string
};
type KsDropdownMenuEvents = {
    onKeyChange: EventName<(number | string)[]>,
    onValueChange: EventName<DropdownMenuItem[]>,
    onVisibleChange: EventName<boolean>,
    onSearchChange: EventName<string>,
    onTabsChange: EventName<string>,
    onHitBottom: EventName<() => void>
};
export type KsDropdownMenuProps = ComponentProps<KsDropdownMenuElement, KsDropdownMenuEvents, KsDropdownMenuSlots>;

const KsDropdownMenu: StencilReactComponent<KsDropdownMenuElement, KsDropdownMenuEvents, KsDropdownMenuSlots> = /*@__PURE__*/ createComponent<KsDropdownMenuElement, KsDropdownMenuEvents, KsDropdownMenuSlots>({
    tagName: 'ks-dropdown-menu',
    elementClass: KsDropdownMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onKeyChange: 'ksKeyChange',
        onValueChange: 'ksValueChange',
        onVisibleChange: 'ksVisibleChange',
        onSearchChange: 'ksSearchChange',
        onTabsChange: 'ksTabsChange',
        onHitBottom: 'ksHitBottom'
    } as KsDropdownMenuEvents,
    slots: {
        header: 'header',
        listHeader: 'listHeader',
        content: 'content',
        footer: 'footer',
        empty: 'empty',
        error: 'error',
        loadFailCtas: 'loadFailCtas'
    } as KsDropdownMenuSlots,
    displayName: 'KsDropdownMenu',
    defineCustomElement: defineKsDropdownMenu,
    tagNameTransform: true
});

export default KsDropdownMenu;
