'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type DrawerCloseReason } from "@fe-infra/keystone";
import { KsDrawer as KsDrawerElement, defineCustomElement as defineKsDrawer } from "@fe-infra/keystone/dist/components/ks-drawer.js";
import React from 'react';

type KsDrawerSlots = {
    /**
     * Slot for content to be displayed in the side navigation area when `withSideNav` is true.
     */
    sideNav: string,
    /**
     * Slot to override the entire inner structure of the drawer.
     */
    wrapper: string,
    /**
     * Slot for custom header content. Overrides `titleText`.
     */
    header: string,
    /**
     * Slot for the main body content of the drawer. Contains the default slot.
     */
    body: string,
    /**
     * Slot for custom footer content. Overrides default confirm/cancel buttons.
     */
    footer: string,
    /**
     * Slot for additional content on the left side of the footer.
     */
    footerOther: string,
    /**
     * Slot to customize the cancel button text or content.
     */
    cancelBtn: string,
    /**
     * Slot to customize the confirm button text or content.
     */
    confirmBtn: string
};
type KsDrawerEvents = {
    onConfirm: EventName<any>,
    onCancel: EventName<any>,
    onClose: EventName<DrawerCloseReason>,
    onExpandChange: EventName<boolean>
};
export type KsDrawerProps = ComponentProps<KsDrawerElement, KsDrawerEvents, KsDrawerSlots>;

const KsDrawer: StencilReactComponent<KsDrawerElement, KsDrawerEvents, KsDrawerSlots> = /*@__PURE__*/ createComponent<KsDrawerElement, KsDrawerEvents, KsDrawerSlots>({
    tagName: 'ks-drawer',
    elementClass: KsDrawerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onConfirm: 'ksConfirm',
        onCancel: 'ksCancel',
        onClose: 'ksClose',
        onExpandChange: 'ksExpandChange'
    } as KsDrawerEvents,
    slots: {
        sideNav: 'sideNav',
        wrapper: 'wrapper',
        header: 'header',
        body: 'body',
        footer: 'footer',
        footerOther: 'footer-other',
        cancelBtn: 'cancel-btn',
        confirmBtn: 'confirm-btn'
    } as KsDrawerSlots,
    displayName: 'KsDrawer',
    defineCustomElement: defineKsDrawer,
    tagNameTransform: true
});

export default KsDrawer;
