'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type DropdownMenuItem } from "@fe-infra/keystone";
import { KsDropdownButton as KsDropdownButtonElement, defineCustomElement as defineKsDropdownButton } from "@fe-infra/keystone/dist/components/ks-dropdown-button.js";
import React from 'react';

type KsDropdownButtonSlots = {
    /**
     * Slot for the footer.
     */
    footer: string,
    /**
     * Slot for the content.
     */
    content: string
};
type KsDropdownButtonEvents = {
    onClickItem: EventName<DropdownMenuItem>,
    onVisibleChange: EventName<boolean>
};
export type KsDropdownButtonProps = ComponentProps<KsDropdownButtonElement, KsDropdownButtonEvents, KsDropdownButtonSlots>;

const KsDropdownButton: StencilReactComponent<KsDropdownButtonElement, KsDropdownButtonEvents, KsDropdownButtonSlots> = /*@__PURE__*/ createComponent<KsDropdownButtonElement, KsDropdownButtonEvents, KsDropdownButtonSlots>({
    tagName: 'ks-dropdown-button',
    elementClass: KsDropdownButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClickItem: 'ksClickItem',
        onVisibleChange: 'ksVisibleChange'
    } as KsDropdownButtonEvents,
    slots: {
        footer: 'footer',
        content: 'content'
    } as KsDropdownButtonSlots,
    displayName: 'KsDropdownButton',
    defineCustomElement: defineKsDropdownButton,
    tagNameTransform: true
});

export default KsDropdownButton;
