'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsEmptyStates as KsEmptyStatesElement, defineCustomElement as defineKsEmptyStates } from "@fe-infra/keystone/dist/components/ks-empty-states.js";
import React from 'react';

type KsEmptyStatesSlots = {
    /**
     * Allows customization of the illustration area.
     */
    illustration: string,
    /**
     * Allows customization of the description content. If provided, this content will be used instead of the `description` prop.
     */
    description: string,
    /**
     * Allows customization of the call-to-action (CTA) buttons area.
     */
    ctas: string
};
type KsEmptyStatesEvents = NonNullable<unknown>;
export type KsEmptyStatesProps = ComponentProps<KsEmptyStatesElement, KsEmptyStatesEvents, KsEmptyStatesSlots>;

const KsEmptyStates: StencilReactComponent<KsEmptyStatesElement, KsEmptyStatesEvents, KsEmptyStatesSlots> = /*@__PURE__*/ createComponent<KsEmptyStatesElement, KsEmptyStatesEvents, KsEmptyStatesSlots>({
    tagName: 'ks-empty-states',
    elementClass: KsEmptyStatesElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsEmptyStatesEvents,
    slots: {
        illustration: 'illustration',
        description: 'description',
        ctas: 'ctas'
    } as KsEmptyStatesSlots,
    displayName: 'KsEmptyStates',
    defineCustomElement: defineKsEmptyStates,
    tagNameTransform: true
});

export default KsEmptyStates;
