'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IPresenterValue } from "@fe-infra/keystone";
import { KsFieldsPresenter as KsFieldsPresenterElement, defineCustomElement as defineKsFieldsPresenter } from "@fe-infra/keystone/dist/components/ks-fields-presenter.js";
import React from 'react';

type KsFieldsPresenterSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for custom placeholder content. Overrides the `placeholder` prop.
     */
    placeholder: string
};
type KsFieldsPresenterEvents = {
    onChange: EventName<IPresenterValue[]>,
    onRemove: EventName<IPresenterValue[]>,
    onClear: EventName<IPresenterValue | IPresenterValue[]>
};
export type KsFieldsPresenterProps = ComponentProps<KsFieldsPresenterElement, KsFieldsPresenterEvents, KsFieldsPresenterSlots>;

const KsFieldsPresenter: StencilReactComponent<KsFieldsPresenterElement, KsFieldsPresenterEvents, KsFieldsPresenterSlots> = /*@__PURE__*/ createComponent<KsFieldsPresenterElement, KsFieldsPresenterEvents, KsFieldsPresenterSlots>({
    tagName: 'ks-fields-presenter',
    elementClass: KsFieldsPresenterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onRemove: 'ksRemove',
        onClear: 'ksClear'
    } as KsFieldsPresenterEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        closeIcon: 'close-icon',
        placeholder: 'placeholder'
    } as KsFieldsPresenterSlots,
    displayName: 'KsFieldsPresenter',
    defineCustomElement: defineKsFieldsPresenter,
    tagNameTransform: true
});

export default KsFieldsPresenter;
