'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createContextComponent } from '@byted-keystone/react-output-target/runtime';
import { type ErrorField, type FormValue } from "@fe-infra/keystone";
import { KsForm as KsFormElement, defineCustomElement as defineKsForm } from "@fe-infra/keystone/dist/components/ks-form.js";
import React from 'react';

type KsFormSlots = NonNullable<unknown>;
type KsFormEvents = {
    onValueChange: EventName<FormValue>,
    onFinish: EventName<FormValue>,
    onFinishFailed: EventName<{
        values: FormValue;
        errorFields: ErrorField[];
    }>
};
export type KsFormProps = ComponentProps<KsFormElement, KsFormEvents, KsFormSlots>;

const KsForm: StencilReactComponent<KsFormElement, KsFormEvents, KsFormSlots> = /*@__PURE__*/ createContextComponent<KsFormElement, KsFormEvents, KsFormSlots>({
    tagName: 'ks-form',
    elementClass: KsFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onValueChange: 'ksValueChange',
        onFinish: 'ksFinish',
        onFinishFailed: 'ksFinishFailed'
    } as KsFormEvents,
    slots: {} as KsFormSlots,
    displayName: 'KsForm',
    defineCustomElement: defineKsForm,
    tagNameTransform: true
});

export default KsForm;
