'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createContextComponent } from '@byted-keystone/react-output-target/runtime';
import { KsFormList as KsFormListElement, defineCustomElement as defineKsFormList } from "@fe-infra/keystone/dist/components/ks-form-list.js";
import React from 'react';

type KsFormListSlots = {
    /**
     * Allows customization of the form list's label. If not provided, the `label` prop will be used as content.
     */
    label: string
};
type KsFormListEvents = NonNullable<unknown>;
export type KsFormListProps = ComponentProps<KsFormListElement, KsFormListEvents, KsFormListSlots>;

const KsFormList: StencilReactComponent<KsFormListElement, KsFormListEvents, KsFormListSlots> = /*@__PURE__*/ createContextComponent<KsFormListElement, KsFormListEvents, KsFormListSlots>({
    tagName: 'ks-form-list',
    elementClass: KsFormListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsFormListEvents,
    slots: { label: 'label' } as KsFormListSlots,
    displayName: 'KsFormList',
    defineCustomElement: defineKsFormList,
    tagNameTransform: true
});

export default KsFormList;
