'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createContextComponent } from '@byted-keystone/react-output-target/runtime';
import { KsFormItem as KsFormItemElement, defineCustomElement as defineKsFormItem } from "@fe-infra/keystone/dist/components/ks-form-item.js";
import React from 'react';

type KsFormItemSlots = {
    /**
     * Allows customization of the form item's label. If not provided, the `label` prop will be used as content.
     */
    label: string
};
type KsFormItemEvents = NonNullable<unknown>;
export type KsFormItemProps = ComponentProps<KsFormItemElement, KsFormItemEvents, KsFormItemSlots>;

const KsFormItem: StencilReactComponent<KsFormItemElement, KsFormItemEvents, KsFormItemSlots> = /*@__PURE__*/ createContextComponent<KsFormItemElement, KsFormItemEvents, KsFormItemSlots>({
    tagName: 'ks-form-item',
    elementClass: KsFormItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsFormItemEvents,
    slots: { label: 'label' } as KsFormItemSlots,
    displayName: 'KsFormItem',
    defineCustomElement: defineKsFormItem,
    tagNameTransform: true
});

export default KsFormItem;
