'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsGlobalAlert as KsGlobalAlertElement, defineCustomElement as defineKsGlobalAlert } from "@fe-infra/keystone/dist/components/ks-global-alert.js";
import React from 'react';

type KsGlobalAlertSlots = {
    /**
     * Slot for a custom icon. If not provided, a default icon based on the `variant` prop is displayed if `showIcon` is true.
     */
    icon: string,
    /**
     * Slot for a custom close button. If not provided, a default close button is displayed if `hasClose` is true.
     */
    closebtn: string,
    /**
     * Slot for the title of the global alert. Displayed above the main content.
     */
    title: string,
    /**
     * Slot for additional descriptive content. Displayed below the default slot content if both are used, or as the main content if the default slot is empty.
     */
    content: string,
    /**
     * Slot for content appended to the right of the main body, often used for actions or links. The `link` slot is typically placed here.
     */
    append: string,
    /**
     * Slot for the link text or interactive element within the clickable link area. This area becomes active if the `append` or `link` slot has content.
     */
    link: string,
    /**
     * Slot for pagination controls, typically used when this banner is part of a series (e.g., in `ks-multiple-global-alert`).
     */
    pagination: string
};
type KsGlobalAlertEvents = {
    onClose: EventName<void>,
    onLinkClick: EventName<void>,
    onAfterClose: EventName<void>
};
export type KsGlobalAlertProps = ComponentProps<KsGlobalAlertElement, KsGlobalAlertEvents, KsGlobalAlertSlots>;

const KsGlobalAlert: StencilReactComponent<KsGlobalAlertElement, KsGlobalAlertEvents, KsGlobalAlertSlots> = /*@__PURE__*/ createComponent<KsGlobalAlertElement, KsGlobalAlertEvents, KsGlobalAlertSlots>({
    tagName: 'ks-global-alert',
    elementClass: KsGlobalAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClose: 'ksClose',
        onLinkClick: 'ksLinkClick',
        onAfterClose: 'ksAfterClose'
    } as KsGlobalAlertEvents,
    slots: {
        icon: 'icon',
        closebtn: 'closebtn',
        title: 'title',
        content: 'content',
        append: 'append',
        link: 'link',
        pagination: 'pagination'
    } as KsGlobalAlertSlots,
    displayName: 'KsGlobalAlert',
    defineCustomElement: defineKsGlobalAlert,
    tagNameTransform: true
});

export default KsGlobalAlert;
