'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsGuidance as KsGuidanceElement, defineCustomElement as defineKsGuidance } from "@fe-infra/keystone/dist/components/ks-guidance.js";
import React from 'react';

type KsGuidanceSlots = {
    /**
     * Allows customization of the icon displayed in the guidance.
     */
    icon: string,
    /**
     * Allows customization of the close button.
     */
    closebtn: string,
    /**
     * Allows customization of the title area of the guidance.
     */
    title: string,
    /**
     * Allows customization of the link area, e.g., for "View more/less" functionality or other action links.
     */
    link: string,
    /**
     * Allows customization of the secondary link area, e.g., for "View more/less" functionality or other action links.
     */
    secondaryLink: string
};
type KsGuidanceEvents = {
    onClose: EventName<void>,
    onLinkClick: EventName<undefined | number | string>,
    onSecondaryLinkClick: EventName<undefined | number | string>,
    onAfterClose: EventName<void>,
    onExpandCollapse: EventName<boolean>
};
export type KsGuidanceProps = ComponentProps<KsGuidanceElement, KsGuidanceEvents, KsGuidanceSlots>;

const KsGuidance: StencilReactComponent<KsGuidanceElement, KsGuidanceEvents, KsGuidanceSlots> = /*@__PURE__*/ createComponent<KsGuidanceElement, KsGuidanceEvents, KsGuidanceSlots>({
    tagName: 'ks-guidance',
    elementClass: KsGuidanceElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClose: 'ksClose',
        onLinkClick: 'ksLinkClick',
        onSecondaryLinkClick: 'ksSecondaryLinkClick',
        onAfterClose: 'ksAfterClose',
        onExpandCollapse: 'ksExpandCollapse'
    } as KsGuidanceEvents,
    slots: {
        icon: 'icon',
        closebtn: 'closebtn',
        title: 'title',
        link: 'link',
        secondaryLink: 'secondaryLink'
    } as KsGuidanceSlots,
    displayName: 'KsGuidance',
    defineCustomElement: defineKsGuidance,
    tagNameTransform: true
});

export default KsGuidance;
