'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsInputPassword as KsInputPasswordElement, defineCustomElement as defineKsInputPassword } from "@fe-infra/keystone/dist/components/ks-input-password.js";
import React from 'react';

type KsInputPasswordSlots = {
    /**
     * Slot for content to be displayed before the password input field.
     */
    prefix: string,
    /**
     * Slot for content to be displayed after the password input field.
     */
    suffix: string
};
type KsInputPasswordEvents = { onChange: EventName<number | string | null> };
export type KsInputPasswordProps = ComponentProps<KsInputPasswordElement, KsInputPasswordEvents, KsInputPasswordSlots>;

const KsInputPassword: StencilReactComponent<KsInputPasswordElement, KsInputPasswordEvents, KsInputPasswordSlots> = /*@__PURE__*/ createComponent<KsInputPasswordElement, KsInputPasswordEvents, KsInputPasswordSlots>({
    tagName: 'ks-input-password',
    elementClass: KsInputPasswordElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsInputPasswordEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix'
    } as KsInputPasswordSlots,
    displayName: 'KsInputPassword',
    defineCustomElement: defineKsInputPassword,
    tagNameTransform: true
});

export default KsInputPassword;
