'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsInput as KsInputElement, defineCustomElement as defineKsInput } from "@fe-infra/keystone/dist/components/ks-input.js";
import React from 'react';

type KsInputSlots = {
    /**
     * Slot for content to be displayed before the input field.
     */
    prefix: string,
    /**
     * Slot for content to be displayed after the input field.
     */
    suffix: string,
    /**
     * Slot for content to be displayed before the input field.
     */
    controlsStart: string,
    /**
     * Slot for content to be displayed after the input field.
     */
    controlsEnd: string,
    /**
     *  Slot for text to be displayed in the input button
     */
    buttonText: string
};
type KsInputEvents = {
    onChange: EventName<string>,
    onClick: EventName<MouseEvent>,
    onClear: EventName<void>,
    onButtonClick: EventName<void>,
    onFocus: EventName<FocusEvent>,
    onBlur: EventName<FocusEvent>,
    onKeydownEnter: EventName<KeyboardEvent>
};
export type KsInputProps = ComponentProps<KsInputElement, KsInputEvents, KsInputSlots>;

const KsInput: StencilReactComponent<KsInputElement, KsInputEvents, KsInputSlots> = /*@__PURE__*/ createComponent<KsInputElement, KsInputEvents, KsInputSlots>({
    tagName: 'ks-input',
    elementClass: KsInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onClick: 'ksClick',
        onClear: 'ksClear',
        onButtonClick: 'ksButtonClick',
        onFocus: 'ksFocus',
        onBlur: 'ksBlur',
        onKeydownEnter: 'ksKeydownEnter'
    } as KsInputEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        controlsStart: 'controls-start',
        controlsEnd: 'controls-end',
        buttonText: 'buttonText'
    } as KsInputSlots,
    displayName: 'KsInput',
    defineCustomElement: defineKsInput,
    tagNameTransform: true
});

export default KsInput;
