'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsInlineAlert as KsInlineAlertElement, defineCustomElement as defineKsInlineAlert } from "@fe-infra/keystone/dist/components/ks-inline-alert.js";
import React from 'react';

type KsInlineAlertSlots = {
    /**
     * Allows customization of the icon displayed in the inline-alert.
     */
    icon: string,
    /**
     * The main content section that displays the alert message text.;
     */
    message: string,
    /**
     * Allows customization of the close button.
     */
    closeBtn: string,
    /**
     * Allows customization of the title area of the inline-alert.
     */
    title: string,
    /**
     * Allows customization of the action area of the inline-alert.
     */
    action: string
};
type KsInlineAlertEvents = {
    onClose: EventName<void>,
    onLinkClick: EventName<void | number | string>,
    onAfterClose: EventName<void>,
    onCollapseChange: EventName<boolean>
};
export type KsInlineAlertProps = ComponentProps<KsInlineAlertElement, KsInlineAlertEvents, KsInlineAlertSlots>;

const KsInlineAlert: StencilReactComponent<KsInlineAlertElement, KsInlineAlertEvents, KsInlineAlertSlots> = /*@__PURE__*/ createComponent<KsInlineAlertElement, KsInlineAlertEvents, KsInlineAlertSlots>({
    tagName: 'ks-inline-alert',
    elementClass: KsInlineAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClose: 'ksClose',
        onLinkClick: 'ksLinkClick',
        onAfterClose: 'ksAfterClose',
        onCollapseChange: 'ksCollapseChange'
    } as KsInlineAlertEvents,
    slots: {
        icon: 'icon',
        message: 'message',
        closeBtn: 'close-btn',
        title: 'title',
        action: 'action'
    } as KsInlineAlertSlots,
    displayName: 'KsInlineAlert',
    defineCustomElement: defineKsInlineAlert,
    tagNameTransform: true
});

export default KsInlineAlert;
