'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IPresenterKey } from "@fe-infra/keystone";
import { KsInputSelector as KsInputSelectorElement, defineCustomElement as defineKsInputSelector } from "@fe-infra/keystone/dist/components/ks-input-selector.js";
import React from 'react';

type KsInputSelectorSlots = {
    /**
     * Allows customization of the content displayed before the input area.
     */
    prefix: string,
    /**
     * Allows customization of the content displayed after the input area, typically for icons.
     */
    suffix: string,
    /**
     * Slot for custom header content within the dropdown panel.
     */
    header: string,
    /**
     * Slot for custom list header content within the dropdown panel.
     */
    listHeader: string,
    /**
     * Allows customization of the content displayed at the bottom of the dropdown panel.
     */
    footer: string,
    /**
     * Allows customization of the content displayed when the dropdown panel has no items to show.
     */
    empty: string,
    /**
     * Slot for cta button to display when the dropdown panel is load fail
     */
    loadFailCtas: string,
    /**
     * Slot for error message.
     */
    error: string,
    /**
     * Slot for custom field content.
     */
    field: string
};
type KsInputSelectorEvents = {
    onInputChange: EventName<string>,
    onRemove: EventName<IPresenterKey | IPresenterKey[]>,
    onChange: EventName<IPresenterKey[] | IPresenterKey>,
    onKeyChange: EventName<(number | string)[]>,
    onVisibleChange: EventName<boolean>,
    onSearchChange: EventName<string>,
    onTabsChange: EventName<string>
};
export type KsInputSelectorProps = ComponentProps<KsInputSelectorElement, KsInputSelectorEvents, KsInputSelectorSlots>;

const KsInputSelector: StencilReactComponent<KsInputSelectorElement, KsInputSelectorEvents, KsInputSelectorSlots> = /*@__PURE__*/ createComponent<KsInputSelectorElement, KsInputSelectorEvents, KsInputSelectorSlots>({
    tagName: 'ks-input-selector',
    elementClass: KsInputSelectorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputChange: 'ksInputChange',
        onRemove: 'ksRemove',
        onChange: 'ksChange',
        onKeyChange: 'ksKeyChange',
        onVisibleChange: 'ksVisibleChange',
        onSearchChange: 'ksSearchChange',
        onTabsChange: 'ksTabsChange'
    } as KsInputSelectorEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        header: 'header',
        listHeader: 'listHeader',
        footer: 'footer',
        empty: 'empty',
        loadFailCtas: 'loadFailCtas',
        error: 'error',
        field: 'field'
    } as KsInputSelectorSlots,
    displayName: 'KsInputSelector',
    defineCustomElement: defineKsInputSelector,
    tagNameTransform: true
});

export default KsInputSelector;
