'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsInputNumber as KsInputNumberElement, defineCustomElement as defineKsInputNumber } from "@fe-infra/keystone/dist/components/ks-input-number.js";
import React from 'react';

type KsInputNumberSlots = {
    /**
     * Slot for content to be displayed before the input field.
     */
    prefix: string,
    /**
     * Slot for content to be displayed after the input field.
     */
    suffix: string
};
type KsInputNumberEvents = { onChange: EventName<number | string> };
export type KsInputNumberProps = ComponentProps<KsInputNumberElement, KsInputNumberEvents, KsInputNumberSlots>;

const KsInputNumber: StencilReactComponent<KsInputNumberElement, KsInputNumberEvents, KsInputNumberSlots> = /*@__PURE__*/ createComponent<KsInputNumberElement, KsInputNumberEvents, KsInputNumberSlots>({
    tagName: 'ks-input-number',
    elementClass: KsInputNumberElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsInputNumberEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix'
    } as KsInputNumberSlots,
    displayName: 'KsInputNumber',
    defineCustomElement: defineKsInputNumber,
    tagNameTransform: true
});

export default KsInputNumber;
