'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsLink as KsLinkElement, defineCustomElement as defineKsLink } from "@fe-infra/keystone/dist/components/ks-link.js";
import React from 'react';

type KsLinkSlots = NonNullable<unknown>;
type KsLinkEvents = NonNullable<unknown>;
export type KsLinkProps = ComponentProps<KsLinkElement, KsLinkEvents, KsLinkSlots>;

const KsLink: StencilReactComponent<KsLinkElement, KsLinkEvents, KsLinkSlots> = /*@__PURE__*/ createComponent<KsLinkElement, KsLinkEvents, KsLinkSlots>({
    tagName: 'ks-link',
    elementClass: KsLinkElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsLinkEvents,
    slots: {} as KsLinkSlots,
    displayName: 'KsLink',
    defineCustomElement: defineKsLink,
    tagNameTransform: true
});

export default KsLink;
