'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsLoadingContainer as KsLoadingContainerElement, defineCustomElement as defineKsLoadingContainer } from "@fe-infra/keystone/dist/components/ks-loading-container.js";
import React from 'react';

type KsLoadingContainerSlots = {
    /**
     * loading component
     */
    loading: string
};
type KsLoadingContainerEvents = NonNullable<unknown>;
export type KsLoadingContainerProps = ComponentProps<KsLoadingContainerElement, KsLoadingContainerEvents, KsLoadingContainerSlots>;

const KsLoadingContainer: StencilReactComponent<KsLoadingContainerElement, KsLoadingContainerEvents, KsLoadingContainerSlots> = /*@__PURE__*/ createComponent<KsLoadingContainerElement, KsLoadingContainerEvents, KsLoadingContainerSlots>({
    tagName: 'ks-loading-container',
    elementClass: KsLoadingContainerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsLoadingContainerEvents,
    slots: { loading: 'loading' } as KsLoadingContainerSlots,
    displayName: 'KsLoadingContainer',
    defineCustomElement: defineKsLoadingContainer,
    tagNameTransform: true
});

export default KsLoadingContainer;
