'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsMenuItem as KsMenuItemElement, defineCustomElement as defineKsMenuItem } from "@fe-infra/keystone/dist/components/ks-menu-item.js";
import React from 'react';

type KsMenuItemSlots = {
    /**
     * Slot for content to be placed before the main menu item text, typically an icon.
     */
    prefix: string,
    /**
     * Slot for content to be placed after the main menu item text.
     */
    suffix: string
};
type KsMenuItemEvents = NonNullable<unknown>;
export type KsMenuItemProps = ComponentProps<KsMenuItemElement, KsMenuItemEvents, KsMenuItemSlots>;

const KsMenuItem: StencilReactComponent<KsMenuItemElement, KsMenuItemEvents, KsMenuItemSlots> = /*@__PURE__*/ createComponent<KsMenuItemElement, KsMenuItemEvents, KsMenuItemSlots>({
    tagName: 'ks-menu-item',
    elementClass: KsMenuItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsMenuItemEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix'
    } as KsMenuItemSlots,
    displayName: 'KsMenuItem',
    defineCustomElement: defineKsMenuItem,
    tagNameTransform: true
});

export default KsMenuItem;
