'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsMenuItemGroup as KsMenuItemGroupElement, defineCustomElement as defineKsMenuItemGroup } from "@fe-infra/keystone/dist/components/ks-menu-item-group.js";
import React from 'react';

type KsMenuItemGroupSlots = {
    /**
     * Slot for the title.
     */
    title: string
};
type KsMenuItemGroupEvents = NonNullable<unknown>;
export type KsMenuItemGroupProps = ComponentProps<KsMenuItemGroupElement, KsMenuItemGroupEvents, KsMenuItemGroupSlots>;

const KsMenuItemGroup: StencilReactComponent<KsMenuItemGroupElement, KsMenuItemGroupEvents, KsMenuItemGroupSlots> = /*@__PURE__*/ createComponent<KsMenuItemGroupElement, KsMenuItemGroupEvents, KsMenuItemGroupSlots>({
    tagName: 'ks-menu-item-group',
    elementClass: KsMenuItemGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsMenuItemGroupEvents,
    slots: { title: 'title' } as KsMenuItemGroupSlots,
    displayName: 'KsMenuItemGroup',
    defineCustomElement: defineKsMenuItemGroup,
    tagNameTransform: true
});

export default KsMenuItemGroup;
