'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMonthRangePanel as KsMonthRangePanelElement, defineCustomElement as defineKsMonthRangePanel } from "@fe-infra/keystone/dist/components/ks-month-range-panel.js";
import React from 'react';

type KsMonthRangePanelSlots = {
    /**
     * preset slot
     */
    preset: string
};
type KsMonthRangePanelEvents = { onChange: EventName<IMultipleDateValue> };
export type KsMonthRangePanelProps = ComponentProps<KsMonthRangePanelElement, KsMonthRangePanelEvents, KsMonthRangePanelSlots>;

const KsMonthRangePanel: StencilReactComponent<KsMonthRangePanelElement, KsMonthRangePanelEvents, KsMonthRangePanelSlots> = /*@__PURE__*/ createComponent<KsMonthRangePanelElement, KsMonthRangePanelEvents, KsMonthRangePanelSlots>({
    tagName: 'ks-month-range-panel',
    elementClass: KsMonthRangePanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsMonthRangePanelEvents,
    slots: { preset: 'preset' } as KsMonthRangePanelSlots,
    displayName: 'KsMonthRangePanel',
    defineCustomElement: defineKsMonthRangePanel,
    tagNameTransform: true
});

export default KsMonthRangePanel;
