'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsMonthPicker as KsMonthPickerElement, defineCustomElement as defineKsMonthPicker } from "@fe-infra/keystone/dist/components/ks-month-picker.js";
import React from 'react';

type KsMonthPickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date options.
     */
    preset: string
};
type KsMonthPickerEvents = {
    onChange: EventName<IDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMonthPickerProps = ComponentProps<KsMonthPickerElement, KsMonthPickerEvents, KsMonthPickerSlots>;

const KsMonthPicker: StencilReactComponent<KsMonthPickerElement, KsMonthPickerEvents, KsMonthPickerSlots> = /*@__PURE__*/ createComponent<KsMonthPickerElement, KsMonthPickerEvents, KsMonthPickerSlots>({
    tagName: 'ks-month-picker',
    elementClass: KsMonthPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMonthPickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsMonthPickerSlots,
    displayName: 'KsMonthPicker',
    defineCustomElement: defineKsMonthPicker,
    tagNameTransform: true
});

export default KsMonthPicker;
