'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMonthRangePicker as KsMonthRangePickerElement, defineCustomElement as defineKsMonthRangePicker } from "@fe-infra/keystone/dist/components/ks-month-range-picker.js";
import React from 'react';

type KsMonthRangePickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date range options.
     */
    preset: string,
    /**
     * Slot for footer content in the picker panel.
     */
    footer: string
};
type KsMonthRangePickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMonthRangePickerProps = ComponentProps<KsMonthRangePickerElement, KsMonthRangePickerEvents, KsMonthRangePickerSlots>;

const KsMonthRangePicker: StencilReactComponent<KsMonthRangePickerElement, KsMonthRangePickerEvents, KsMonthRangePickerSlots> = /*@__PURE__*/ createComponent<KsMonthRangePickerElement, KsMonthRangePickerEvents, KsMonthRangePickerSlots>({
    tagName: 'ks-month-range-picker',
    elementClass: KsMonthRangePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMonthRangePickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset',
        footer: 'footer'
    } as KsMonthRangePickerSlots,
    displayName: 'KsMonthRangePicker',
    defineCustomElement: defineKsMonthRangePicker,
    tagNameTransform: true
});

export default KsMonthRangePicker;
