'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type ModalCloseReason } from "@fe-infra/keystone";
import { KsModal as KsModalElement, defineCustomElement as defineKsModal } from "@fe-infra/keystone/dist/components/ks-modal.js";
import React from 'react';

type KsModalSlots = {
    /**
     * Allows customization of the modal's header content. If not provided, `titleText` prop will be used.
     */
    header: string,
    /**
     * Allows customization of the description text displayed below the title in the header. If not provided, `descriptionText` prop will be used.
     */
    description: string,
    /**
     * Allows customization of the main content area of the modal.
     */
    body: string,
    /**
     * Allows customization of the whole part of body
     */
    bodyContainer: string,
    /**
     * Allows customization of the modal's footer content. If not provided, default buttons (confirm/cancel) will be rendered based on props.
     */
    footer: string,
    /**
     * Allows customization of an area in the footer, typically to the left of the standard action buttons.
     */
    footerOther: string,
    /**
     * Allows customization of the cancel button's content. If not provided, `cancelText` prop or a default localized string will be used.
     */
    cancelBtn: string,
    /**
     * Allows customization of the confirm button's content. If not provided, `confirmText` prop or a default localized string will be used.
     */
    confirmBtn: string,
    /**
     * Allows customization of the close button (typically an 'X' icon) in the header.
     */
    closeBtn: string,
    /**
     * Allows replacing the entire inner structure of the modal (advanced usage).
     */
    wrapper: string
};
type KsModalEvents = {
    onConfirm: EventName<any>,
    onCancel: EventName<any>,
    onClose: EventName<ModalCloseReason>
};
export type KsModalProps = ComponentProps<KsModalElement, KsModalEvents, KsModalSlots>;

const KsModal: StencilReactComponent<KsModalElement, KsModalEvents, KsModalSlots> = /*@__PURE__*/ createComponent<KsModalElement, KsModalEvents, KsModalSlots>({
    tagName: 'ks-modal',
    elementClass: KsModalElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onConfirm: 'ksConfirm',
        onCancel: 'ksCancel',
        onClose: 'ksClose'
    } as KsModalEvents,
    slots: {
        header: 'header',
        description: 'description',
        body: 'body',
        bodyContainer: 'body-container',
        footer: 'footer',
        footerOther: 'footer-other',
        cancelBtn: 'cancel-btn',
        confirmBtn: 'confirm-btn',
        closeBtn: 'close-btn',
        wrapper: 'wrapper'
    } as KsModalSlots,
    displayName: 'KsModal',
    defineCustomElement: defineKsModal,
    tagNameTransform: true
});

export default KsModal;
