'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleWeekPicker as KsMultipleWeekPickerElement, defineCustomElement as defineKsMultipleWeekPicker } from "@fe-infra/keystone/dist/components/ks-multiple-week-picker.js";
import React from 'react';

type KsMultipleWeekPickerSlots = {
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset week options.
     */
    preset: string
};
type KsMultipleWeekPickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMultipleWeekPickerProps = ComponentProps<KsMultipleWeekPickerElement, KsMultipleWeekPickerEvents, KsMultipleWeekPickerSlots>;

const KsMultipleWeekPicker: StencilReactComponent<KsMultipleWeekPickerElement, KsMultipleWeekPickerEvents, KsMultipleWeekPickerSlots> = /*@__PURE__*/ createComponent<KsMultipleWeekPickerElement, KsMultipleWeekPickerEvents, KsMultipleWeekPickerSlots>({
    tagName: 'ks-multiple-week-picker',
    elementClass: KsMultipleWeekPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMultipleWeekPickerEvents,
    slots: {
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsMultipleWeekPickerSlots,
    displayName: 'KsMultipleWeekPicker',
    defineCustomElement: defineKsMultipleWeekPicker,
    tagNameTransform: true
});

export default KsMultipleWeekPicker;
