'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleQuarterPicker as KsMultipleQuarterPickerElement, defineCustomElement as defineKsMultipleQuarterPicker } from "@fe-infra/keystone/dist/components/ks-multiple-quarter-picker.js";
import React from 'react';

type KsMultipleQuarterPickerSlots = {
    /**
     * 后缀
     */
    suffix: string,
    /**
     * 展开指示icon
     */
    showIcon: string,
    /**
     * 清除icon
     */
    closeIcon: string,
    /**
     * preset slot
     */
    preset: string
};
type KsMultipleQuarterPickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMultipleQuarterPickerProps = ComponentProps<KsMultipleQuarterPickerElement, KsMultipleQuarterPickerEvents, KsMultipleQuarterPickerSlots>;

const KsMultipleQuarterPicker: StencilReactComponent<KsMultipleQuarterPickerElement, KsMultipleQuarterPickerEvents, KsMultipleQuarterPickerSlots> = /*@__PURE__*/ createComponent<KsMultipleQuarterPickerElement, KsMultipleQuarterPickerEvents, KsMultipleQuarterPickerSlots>({
    tagName: 'ks-multiple-quarter-picker',
    elementClass: KsMultipleQuarterPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMultipleQuarterPickerEvents,
    slots: {
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsMultipleQuarterPickerSlots,
    displayName: 'KsMultipleQuarterPicker',
    defineCustomElement: defineKsMultipleQuarterPicker,
    tagNameTransform: true
});

export default KsMultipleQuarterPicker;
