'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleMonthPicker as KsMultipleMonthPickerElement, defineCustomElement as defineKsMultipleMonthPicker } from "@fe-infra/keystone/dist/components/ks-multiple-month-picker.js";
import React from 'react';

type KsMultipleMonthPickerSlots = {
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date options.
     */
    preset: string
};
type KsMultipleMonthPickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMultipleMonthPickerProps = ComponentProps<KsMultipleMonthPickerElement, KsMultipleMonthPickerEvents, KsMultipleMonthPickerSlots>;

const KsMultipleMonthPicker: StencilReactComponent<KsMultipleMonthPickerElement, KsMultipleMonthPickerEvents, KsMultipleMonthPickerSlots> = /*@__PURE__*/ createComponent<KsMultipleMonthPickerElement, KsMultipleMonthPickerEvents, KsMultipleMonthPickerSlots>({
    tagName: 'ks-multiple-month-picker',
    elementClass: KsMultipleMonthPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMultipleMonthPickerEvents,
    slots: {
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsMultipleMonthPickerSlots,
    displayName: 'KsMultipleMonthPicker',
    defineCustomElement: defineKsMultipleMonthPicker,
    tagNameTransform: true
});

export default KsMultipleMonthPicker;
