'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsMultipleInput as KsMultipleInputElement, defineCustomElement as defineKsMultipleInput } from "@fe-infra/keystone/dist/components/ks-multiple-input.js";
import React from 'react';

type KsMultipleInputSlots = {
    /**
     * Allows customization of the content displayed before the input field area.
     */
    prefix: string,
    /**
     * Allows customization of the content displayed after the input field area.
     */
    suffix: string
};
type KsMultipleInputEvents = {
    onChange: EventName<string[]>,
    onRemove: EventName<string[]>,
    onBlur: EventName<FocusEvent>
};
export type KsMultipleInputProps = ComponentProps<KsMultipleInputElement, KsMultipleInputEvents, KsMultipleInputSlots>;

const KsMultipleInput: StencilReactComponent<KsMultipleInputElement, KsMultipleInputEvents, KsMultipleInputSlots> = /*@__PURE__*/ createComponent<KsMultipleInputElement, KsMultipleInputEvents, KsMultipleInputSlots>({
    tagName: 'ks-multiple-input',
    elementClass: KsMultipleInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onRemove: 'ksRemove',
        onBlur: 'ksBlur'
    } as KsMultipleInputEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix'
    } as KsMultipleInputSlots,
    displayName: 'KsMultipleInput',
    defineCustomElement: defineKsMultipleInput,
    tagNameTransform: true
});

export default KsMultipleInput;
