'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type CascaderItemValue } from "@fe-infra/keystone";
import { KsMultipleCascader as KsMultipleCascaderElement, defineCustomElement as defineKsMultipleCascader } from "@fe-infra/keystone/dist/components/ks-multiple-cascader.js";
import React from 'react';

type KsMultipleCascaderSlots = {
    /**
     * Slot for content at the top of the dropdown panel.
     */
    panelHeader: string,
    /**
     * Slot for content at the bottom of the dropdown panel.
     */
    panelFooter: string,
    /**
     * Slot for prefix content before the input display.
     */
    prefix: string,
    /**
     * Slot for a custom expansion indicator icon.
     */
    showIcon: string,
    /**
     * Slot for a custom clear icon.
     */
    closeIcon: string,
    /**
     * Slot for suffix content after the input display (overrides show-icon & close-icon).
     */
    suffix: string,
    /**
     * Slot for selected content.
     */
    selected: string
};
type KsMultipleCascaderEvents = {
    onChange: EventName<CascaderItemValue[]>,
    onVisibleChange: EventName<boolean>,
    onSearchChange: EventName<string>
};
export type KsMultipleCascaderProps = ComponentProps<KsMultipleCascaderElement, KsMultipleCascaderEvents, KsMultipleCascaderSlots>;

const KsMultipleCascader: StencilReactComponent<KsMultipleCascaderElement, KsMultipleCascaderEvents, KsMultipleCascaderSlots> = /*@__PURE__*/ createComponent<KsMultipleCascaderElement, KsMultipleCascaderEvents, KsMultipleCascaderSlots>({
    tagName: 'ks-multiple-cascader',
    elementClass: KsMultipleCascaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onVisibleChange: 'ksVisibleChange',
        onSearchChange: 'ksSearchChange'
    } as KsMultipleCascaderEvents,
    slots: {
        panelHeader: 'panel-header',
        panelFooter: 'panel-footer',
        prefix: 'prefix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        suffix: 'suffix',
        selected: 'selected'
    } as KsMultipleCascaderSlots,
    displayName: 'KsMultipleCascader',
    defineCustomElement: defineKsMultipleCascader,
    tagNameTransform: true
});

export default KsMultipleCascader;
