'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleQuarterPanel as KsMultipleQuarterPanelElement, defineCustomElement as defineKsMultipleQuarterPanel } from "@fe-infra/keystone/dist/components/ks-multiple-quarter-panel.js";
import React from 'react';

type KsMultipleQuarterPanelSlots = {
    /**
     * preset slot
     */
    preset: string
};
type KsMultipleQuarterPanelEvents = { onChange: EventName<IMultipleDateValue> };
export type KsMultipleQuarterPanelProps = ComponentProps<KsMultipleQuarterPanelElement, KsMultipleQuarterPanelEvents, KsMultipleQuarterPanelSlots>;

const KsMultipleQuarterPanel: StencilReactComponent<KsMultipleQuarterPanelElement, KsMultipleQuarterPanelEvents, KsMultipleQuarterPanelSlots> = /*@__PURE__*/ createComponent<KsMultipleQuarterPanelElement, KsMultipleQuarterPanelEvents, KsMultipleQuarterPanelSlots>({
    tagName: 'ks-multiple-quarter-panel',
    elementClass: KsMultipleQuarterPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsMultipleQuarterPanelEvents,
    slots: { preset: 'preset' } as KsMultipleQuarterPanelSlots,
    displayName: 'KsMultipleQuarterPanel',
    defineCustomElement: defineKsMultipleQuarterPanel,
    tagNameTransform: true
});

export default KsMultipleQuarterPanel;
