'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsMultipleGlobalAlert as KsMultipleGlobalAlertElement, defineCustomElement as defineKsMultipleGlobalAlert } from "@fe-infra/keystone/dist/components/ks-multiple-global-alert.js";
import React from 'react';

type KsMultipleGlobalAlertSlots = {
    /**
     * Slot for a custom title for the current alert. If provided, it overrides the title from the `infos` prop for the currently displayed item.
     */
    title: string,
    /**
     * Slot for custom link content for the current alert. If provided, it overrides the link data from the `infos` prop for the currently displayed item.
     */
    link: string,
    /**
     * Slot for custom main content for the current alert. If provided, it overrides the content from the `infos` prop for the currently displayed item.
     */
    content: string
};
type KsMultipleGlobalAlertEvents = {
    onClose: EventName<number>,
    onLinkClick: EventName<number>,
    onAfterClose: EventName<number>
};
export type KsMultipleGlobalAlertProps = ComponentProps<KsMultipleGlobalAlertElement, KsMultipleGlobalAlertEvents, KsMultipleGlobalAlertSlots>;

const KsMultipleGlobalAlert: StencilReactComponent<KsMultipleGlobalAlertElement, KsMultipleGlobalAlertEvents, KsMultipleGlobalAlertSlots> = /*@__PURE__*/ createComponent<KsMultipleGlobalAlertElement, KsMultipleGlobalAlertEvents, KsMultipleGlobalAlertSlots>({
    tagName: 'ks-multiple-global-alert',
    elementClass: KsMultipleGlobalAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClose: 'ksClose',
        onLinkClick: 'ksLinkClick',
        onAfterClose: 'ksAfterClose'
    } as KsMultipleGlobalAlertEvents,
    slots: {
        title: 'title',
        link: 'link',
        content: 'content'
    } as KsMultipleGlobalAlertSlots,
    displayName: 'KsMultipleGlobalAlert',
    defineCustomElement: defineKsMultipleGlobalAlert,
    tagNameTransform: true
});

export default KsMultipleGlobalAlert;
