'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleYearPicker as KsMultipleYearPickerElement, defineCustomElement as defineKsMultipleYearPicker } from "@fe-infra/keystone/dist/components/ks-multiple-year-picker.js";
import React from 'react';

type KsMultipleYearPickerSlots = {
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset year options.
     */
    preset: string
};
type KsMultipleYearPickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMultipleYearPickerProps = ComponentProps<KsMultipleYearPickerElement, KsMultipleYearPickerEvents, KsMultipleYearPickerSlots>;

const KsMultipleYearPicker: StencilReactComponent<KsMultipleYearPickerElement, KsMultipleYearPickerEvents, KsMultipleYearPickerSlots> = /*@__PURE__*/ createComponent<KsMultipleYearPickerElement, KsMultipleYearPickerEvents, KsMultipleYearPickerSlots>({
    tagName: 'ks-multiple-year-picker',
    elementClass: KsMultipleYearPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMultipleYearPickerEvents,
    slots: {
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsMultipleYearPickerSlots,
    displayName: 'KsMultipleYearPicker',
    defineCustomElement: defineKsMultipleYearPicker,
    tagNameTransform: true
});

export default KsMultipleYearPicker;
