'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleDatePicker as KsMultipleDatePickerElement, defineCustomElement as defineKsMultipleDatePicker } from "@fe-infra/keystone/dist/components/ks-multiple-date-picker.js";
import React from 'react';

type KsMultipleDatePickerSlots = {
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset date options.
     */
    preset: string
};
type KsMultipleDatePickerEvents = {
    onChange: EventName<IMultipleDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsMultipleDatePickerProps = ComponentProps<KsMultipleDatePickerElement, KsMultipleDatePickerEvents, KsMultipleDatePickerSlots>;

const KsMultipleDatePicker: StencilReactComponent<KsMultipleDatePickerElement, KsMultipleDatePickerEvents, KsMultipleDatePickerSlots> = /*@__PURE__*/ createComponent<KsMultipleDatePickerElement, KsMultipleDatePickerEvents, KsMultipleDatePickerSlots>({
    tagName: 'ks-multiple-date-picker',
    elementClass: KsMultipleDatePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsMultipleDatePickerEvents,
    slots: {
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsMultipleDatePickerSlots,
    displayName: 'KsMultipleDatePicker',
    defineCustomElement: defineKsMultipleDatePicker,
    tagNameTransform: true
});

export default KsMultipleDatePicker;
