'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IMultipleDateValue } from "@fe-infra/keystone";
import { KsMultipleMonthRangePanel as KsMultipleMonthRangePanelElement, defineCustomElement as defineKsMultipleMonthRangePanel } from "@fe-infra/keystone/dist/components/ks-multiple-month-range-panel.js";
import React from 'react';

type KsMultipleMonthRangePanelSlots = {
    /**
     * preset slot
     */
    preset: string
};
type KsMultipleMonthRangePanelEvents = {
    onChange: EventName<IMultipleDateValue>,
    onDateHover: EventName<Date>,
    onViewDateChange: EventName<Date>
};
export type KsMultipleMonthRangePanelProps = ComponentProps<KsMultipleMonthRangePanelElement, KsMultipleMonthRangePanelEvents, KsMultipleMonthRangePanelSlots>;

const KsMultipleMonthRangePanel: StencilReactComponent<KsMultipleMonthRangePanelElement, KsMultipleMonthRangePanelEvents, KsMultipleMonthRangePanelSlots> = /*@__PURE__*/ createComponent<KsMultipleMonthRangePanelElement, KsMultipleMonthRangePanelEvents, KsMultipleMonthRangePanelSlots>({
    tagName: 'ks-multiple-month-range-panel',
    elementClass: KsMultipleMonthRangePanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onDateHover: 'ksDateHover',
        onViewDateChange: 'ksViewDateChange'
    } as KsMultipleMonthRangePanelEvents,
    slots: { preset: 'preset' } as KsMultipleMonthRangePanelSlots,
    displayName: 'KsMultipleMonthRangePanel',
    defineCustomElement: defineKsMultipleMonthRangePanel,
    tagNameTransform: true
});

export default KsMultipleMonthRangePanel;
