'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsNuxPopover as KsNuxPopoverElement, defineCustomElement as defineKsNuxPopover } from "@fe-infra/keystone/dist/components/ks-nux-popover.js";
import React from 'react';

type KsNuxPopoverSlots = {
    /**
     * content of the popover
     */
    content: string
};
type KsNuxPopoverEvents = {
    onButtonClick: EventName<{
        key: number | string;
        text: string;
        buttonKey?: string | number;
    }>,
    onVisibleChange: EventName<boolean>
};
export type KsNuxPopoverProps = ComponentProps<KsNuxPopoverElement, KsNuxPopoverEvents, KsNuxPopoverSlots>;

const KsNuxPopover: StencilReactComponent<KsNuxPopoverElement, KsNuxPopoverEvents, KsNuxPopoverSlots> = /*@__PURE__*/ createComponent<KsNuxPopoverElement, KsNuxPopoverEvents, KsNuxPopoverSlots>({
    tagName: 'ks-nux-popover',
    elementClass: KsNuxPopoverElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onButtonClick: 'ksButtonClick',
        onVisibleChange: 'ksVisibleChange'
    } as KsNuxPopoverEvents,
    slots: { content: 'content' } as KsNuxPopoverSlots,
    displayName: 'KsNuxPopover',
    defineCustomElement: defineKsNuxPopover,
    tagNameTransform: true
});

export default KsNuxPopover;
