'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsOverlay as KsOverlayElement, defineCustomElement as defineKsOverlay } from "@fe-infra/keystone/dist/components/ks-overlay.js";
import React from 'react';

type KsOverlaySlots = NonNullable<unknown>;
type KsOverlayEvents = { onClose: EventName<void> };
export type KsOverlayProps = ComponentProps<KsOverlayElement, KsOverlayEvents, KsOverlaySlots>;

const KsOverlay: StencilReactComponent<KsOverlayElement, KsOverlayEvents, KsOverlaySlots> = /*@__PURE__*/ createComponent<KsOverlayElement, KsOverlayEvents, KsOverlaySlots>({
    tagName: 'ks-overlay',
    elementClass: KsOverlayElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onClose: 'close' } as KsOverlayEvents,
    slots: {} as KsOverlaySlots,
    displayName: 'KsOverlay',
    defineCustomElement: defineKsOverlay,
    tagNameTransform: true
});

export default KsOverlay;
