'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsPagination as KsPaginationElement, defineCustomElement as defineKsPagination } from "@fe-infra/keystone/dist/components/ks-pagination.js";
import React from 'react';

type KsPaginationSlots = NonNullable<unknown>;
type KsPaginationEvents = {
    onPageChange: EventName<number>,
    onPageSizeChange: EventName<{ page: number; pageSize: number }>
};
export type KsPaginationProps = ComponentProps<KsPaginationElement, KsPaginationEvents, KsPaginationSlots>;

const KsPagination: StencilReactComponent<KsPaginationElement, KsPaginationEvents, KsPaginationSlots> = /*@__PURE__*/ createComponent<KsPaginationElement, KsPaginationEvents, KsPaginationSlots>({
    tagName: 'ks-pagination',
    elementClass: KsPaginationElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onPageChange: 'ksPageChange',
        onPageSizeChange: 'ksPageSizeChange'
    } as KsPaginationEvents,
    slots: {} as KsPaginationSlots,
    displayName: 'KsPagination',
    defineCustomElement: defineKsPagination,
    tagNameTransform: true
});

export default KsPagination;
