'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsPopover as KsPopoverElement, defineCustomElement as defineKsPopover } from "@fe-infra/keystone/dist/components/ks-popover.js";
import React from 'react';

type KsPopoverSlots = {
    /**
     * Slot for the main content to be displayed inside the popover. This is an alternative to using the `content` prop.
     */
    content: string,
    /**
     * Slot for more complex body content within the popover. Can be used if the `content` slot or prop is not sufficient.
     */
    body: string
};
type KsPopoverEvents = {
    onVisibleChange: EventName<boolean>,
    onAfterOpen: EventName<void>,
    onAfterClose: EventName<void>
};
export type KsPopoverProps = ComponentProps<KsPopoverElement, KsPopoverEvents, KsPopoverSlots>;

const KsPopover: StencilReactComponent<KsPopoverElement, KsPopoverEvents, KsPopoverSlots> = /*@__PURE__*/ createComponent<KsPopoverElement, KsPopoverEvents, KsPopoverSlots>({
    tagName: 'ks-popover',
    elementClass: KsPopoverElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onVisibleChange: 'ksVisibleChange',
        onAfterOpen: 'ksAfterOpen',
        onAfterClose: 'ksAfterClose'
    } as KsPopoverEvents,
    slots: {
        content: 'content',
        body: 'body'
    } as KsPopoverSlots,
    displayName: 'KsPopover',
    defineCustomElement: defineKsPopover,
    tagNameTransform: true
});

export default KsPopover;
