'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsProgress as KsProgressElement, defineCustomElement as defineKsProgress } from "@fe-infra/keystone/dist/components/ks-progress.js";
import React from 'react';

type KsProgressSlots = {
    /**
     * Allows customization of the help text displayed below the progress indicator. This slot is only rendered when the `variant` is 'bar'.
     */
    helpText: string,
    /**
     *  Allows customization of the percent text
     */
    percentText: string
};
type KsProgressEvents = NonNullable<unknown>;
export type KsProgressProps = ComponentProps<KsProgressElement, KsProgressEvents, KsProgressSlots>;

const KsProgress: StencilReactComponent<KsProgressElement, KsProgressEvents, KsProgressSlots> = /*@__PURE__*/ createComponent<KsProgressElement, KsProgressEvents, KsProgressSlots>({
    tagName: 'ks-progress',
    elementClass: KsProgressElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsProgressEvents,
    slots: {
        helpText: 'helpText',
        percentText: 'percentText'
    } as KsProgressSlots,
    displayName: 'KsProgress',
    defineCustomElement: defineKsProgress,
    tagNameTransform: true
});

export default KsProgress;
