'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsQuarterPicker as KsQuarterPickerElement, defineCustomElement as defineKsQuarterPicker } from "@fe-infra/keystone/dist/components/ks-quarter-picker.js";
import React from 'react';

type KsQuarterPickerSlots = {
    /**
     * 前缀
     */
    prefix: string,
    /**
     * 后缀
     */
    suffix: string,
    /**
     * 展开指示icon
     */
    showIcon: string,
    /**
     * 清除icon
     */
    closeIcon: string,
    /**
     * preset slot
     */
    preset: string
};
type KsQuarterPickerEvents = {
    onChange: EventName<IDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsQuarterPickerProps = ComponentProps<KsQuarterPickerElement, KsQuarterPickerEvents, KsQuarterPickerSlots>;

const KsQuarterPicker: StencilReactComponent<KsQuarterPickerElement, KsQuarterPickerEvents, KsQuarterPickerSlots> = /*@__PURE__*/ createComponent<KsQuarterPickerElement, KsQuarterPickerEvents, KsQuarterPickerSlots>({
    tagName: 'ks-quarter-picker',
    elementClass: KsQuarterPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsQuarterPickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsQuarterPickerSlots,
    displayName: 'KsQuarterPicker',
    defineCustomElement: defineKsQuarterPicker,
    tagNameTransform: true
});

export default KsQuarterPicker;
