'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsQuarterPanel as KsQuarterPanelElement, defineCustomElement as defineKsQuarterPanel } from "@fe-infra/keystone/dist/components/ks-quarter-panel.js";
import React from 'react';

type KsQuarterPanelSlots = {
    /**
     * preset slot
     */
    preset: string
};
type KsQuarterPanelEvents = { onChange: EventName<IDateValue> };
export type KsQuarterPanelProps = ComponentProps<KsQuarterPanelElement, KsQuarterPanelEvents, KsQuarterPanelSlots>;

const KsQuarterPanel: StencilReactComponent<KsQuarterPanelElement, KsQuarterPanelEvents, KsQuarterPanelSlots> = /*@__PURE__*/ createComponent<KsQuarterPanelElement, KsQuarterPanelEvents, KsQuarterPanelSlots>({
    tagName: 'ks-quarter-panel',
    elementClass: KsQuarterPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsQuarterPanelEvents,
    slots: { preset: 'preset' } as KsQuarterPanelSlots,
    displayName: 'KsQuarterPanel',
    defineCustomElement: defineKsQuarterPanel,
    tagNameTransform: true
});

export default KsQuarterPanel;
