'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsRadio as KsRadioElement, defineCustomElement as defineKsRadio } from "@fe-infra/keystone/dist/components/ks-radio.js";
import React from 'react';

type KsRadioSlots = {
    /**
     * Slot for providing additional descriptive text for the radio option.
     */
    description: string,
    /**
     * Slot for adding custom functional components or complex structures alongside the radio button.
     */
    content: string,
    /**
     * Slot for the label.
     */
    label: string,
    /**
     * Slot for the suffix.
     */
    suffix: string
};
type KsRadioEvents = { onChange: EventName<boolean> };
export type KsRadioProps = ComponentProps<KsRadioElement, KsRadioEvents, KsRadioSlots>;

const KsRadio: StencilReactComponent<KsRadioElement, KsRadioEvents, KsRadioSlots> = /*@__PURE__*/ createComponent<KsRadioElement, KsRadioEvents, KsRadioSlots>({
    tagName: 'ks-radio',
    elementClass: KsRadioElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsRadioEvents,
    slots: {
        description: 'description',
        content: 'content',
        label: 'label',
        suffix: 'suffix'
    } as KsRadioSlots,
    displayName: 'KsRadio',
    defineCustomElement: defineKsRadio,
    tagNameTransform: true
});

export default KsRadio;
