'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type RadioValue } from "@fe-infra/keystone";
import { KsRadioGroup as KsRadioGroupElement, defineCustomElement as defineKsRadioGroup } from "@fe-infra/keystone/dist/components/ks-radio-group.js";
import React from 'react';

type KsRadioGroupSlots = NonNullable<unknown>;
type KsRadioGroupEvents = { onChange: EventName<RadioValue> };
export type KsRadioGroupProps = ComponentProps<KsRadioGroupElement, KsRadioGroupEvents, KsRadioGroupSlots>;

const KsRadioGroup: StencilReactComponent<KsRadioGroupElement, KsRadioGroupEvents, KsRadioGroupSlots> = /*@__PURE__*/ createComponent<KsRadioGroupElement, KsRadioGroupEvents, KsRadioGroupSlots>({
    tagName: 'ks-radio-group',
    elementClass: KsRadioGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsRadioGroupEvents,
    slots: {} as KsRadioGroupSlots,
    displayName: 'KsRadioGroup',
    defineCustomElement: defineKsRadioGroup,
    tagNameTransform: true
});

export default KsRadioGroup;
