'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsScrollbar as KsScrollbarElement, defineCustomElement as defineKsScrollbar } from "@fe-infra/keystone/dist/components/ks-scrollbar.js";
import React from 'react';

type KsScrollbarSlots = NonNullable<unknown>;
type KsScrollbarEvents = NonNullable<unknown>;
export type KsScrollbarProps = ComponentProps<KsScrollbarElement, KsScrollbarEvents, KsScrollbarSlots>;

const KsScrollbar: StencilReactComponent<KsScrollbarElement, KsScrollbarEvents, KsScrollbarSlots> = /*@__PURE__*/ createComponent<KsScrollbarElement, KsScrollbarEvents, KsScrollbarSlots>({
    tagName: 'ks-scrollbar',
    elementClass: KsScrollbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsScrollbarEvents,
    slots: {} as KsScrollbarSlots,
    displayName: 'KsScrollbar',
    defineCustomElement: defineKsScrollbar,
    tagNameTransform: true
});

export default KsScrollbar;
