'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSegmentedGroup as KsSegmentedGroupElement, defineCustomElement as defineKsSegmentedGroup } from "@fe-infra/keystone/dist/components/ks-segmented-group.js";
import React from 'react';

type KsSegmentedGroupSlots = NonNullable<unknown>;
type KsSegmentedGroupEvents = { onChange: EventName<string | number> };
export type KsSegmentedGroupProps = ComponentProps<KsSegmentedGroupElement, KsSegmentedGroupEvents, KsSegmentedGroupSlots>;

const KsSegmentedGroup: StencilReactComponent<KsSegmentedGroupElement, KsSegmentedGroupEvents, KsSegmentedGroupSlots> = /*@__PURE__*/ createComponent<KsSegmentedGroupElement, KsSegmentedGroupEvents, KsSegmentedGroupSlots>({
    tagName: 'ks-segmented-group',
    elementClass: KsSegmentedGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsSegmentedGroupEvents,
    slots: {} as KsSegmentedGroupSlots,
    displayName: 'KsSegmentedGroup',
    defineCustomElement: defineKsSegmentedGroup,
    tagNameTransform: true
});

export default KsSegmentedGroup;
