'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSegmentedItem as KsSegmentedItemElement, defineCustomElement as defineKsSegmentedItem } from "@fe-infra/keystone/dist/components/ks-segmented-item.js";
import React from 'react';

type KsSegmentedItemSlots = NonNullable<unknown>;
type KsSegmentedItemEvents = { onClick: EventName<string | number> };
export type KsSegmentedItemProps = ComponentProps<KsSegmentedItemElement, KsSegmentedItemEvents, KsSegmentedItemSlots>;

const KsSegmentedItem: StencilReactComponent<KsSegmentedItemElement, KsSegmentedItemEvents, KsSegmentedItemSlots> = /*@__PURE__*/ createComponent<KsSegmentedItemElement, KsSegmentedItemEvents, KsSegmentedItemSlots>({
    tagName: 'ks-segmented-item',
    elementClass: KsSegmentedItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onClick: 'ksClick' } as KsSegmentedItemEvents,
    slots: {} as KsSegmentedItemSlots,
    displayName: 'KsSegmentedItem',
    defineCustomElement: defineKsSegmentedItem,
    tagNameTransform: true
});

export default KsSegmentedItem;
