'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSearch as KsSearchElement, defineCustomElement as defineKsSearch } from "@fe-infra/keystone/dist/components/ks-search.js";
import React from 'react';

type KsSearchSlots = NonNullable<unknown>;
type KsSearchEvents = {
    onChange: EventName<string>,
    onSearch: EventName<string>,
    onClear: EventName<string>,
    onCategoryChange: EventName<string>
};
export type KsSearchProps = ComponentProps<KsSearchElement, KsSearchEvents, KsSearchSlots>;

const KsSearch: StencilReactComponent<KsSearchElement, KsSearchEvents, KsSearchSlots> = /*@__PURE__*/ createComponent<KsSearchElement, KsSearchEvents, KsSearchSlots>({
    tagName: 'ks-search',
    elementClass: KsSearchElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onSearch: 'ksSearch',
        onClear: 'ksClear',
        onCategoryChange: 'ksCategoryChange'
    } as KsSearchEvents,
    slots: {} as KsSearchSlots,
    displayName: 'KsSearch',
    defineCustomElement: defineKsSearch,
    tagNameTransform: true
});

export default KsSearch;
