'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSideNavigation as KsSideNavigationElement, defineCustomElement as defineKsSideNavigation } from "@fe-infra/keystone/dist/components/ks-side-navigation.js";
import React from 'react';

type KsSideNavigationSlots = {
    /**
     * Slot for the main title text of the side navigation.
     */
    title: string,
    /**
     * Slot for placing additional components between the title section and the main navigation content.
     */
    banner: string,
    /**
     * Slot for content to be placed at the bottom of the side navigation panel.
     */
    footer: string
};
type KsSideNavigationEvents = { onSelect: EventName<string> };
export type KsSideNavigationProps = ComponentProps<KsSideNavigationElement, KsSideNavigationEvents, KsSideNavigationSlots>;

const KsSideNavigation: StencilReactComponent<KsSideNavigationElement, KsSideNavigationEvents, KsSideNavigationSlots> = /*@__PURE__*/ createComponent<KsSideNavigationElement, KsSideNavigationEvents, KsSideNavigationSlots>({
    tagName: 'ks-side-navigation',
    elementClass: KsSideNavigationElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSelect: 'ksSelect' } as KsSideNavigationEvents,
    slots: {
        title: 'title',
        banner: 'banner',
        footer: 'footer'
    } as KsSideNavigationSlots,
    displayName: 'KsSideNavigation',
    defineCustomElement: defineKsSideNavigation,
    tagNameTransform: true
});

export default KsSideNavigation;
