'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSkeletonCard as KsSkeletonCardElement, defineCustomElement as defineKsSkeletonCard } from "@fe-infra/keystone/dist/components/ks-skeleton-card.js";
import React from 'react';

type KsSkeletonCardSlots = NonNullable<unknown>;
type KsSkeletonCardEvents = NonNullable<unknown>;
export type KsSkeletonCardProps = ComponentProps<KsSkeletonCardElement, KsSkeletonCardEvents, KsSkeletonCardSlots>;

const KsSkeletonCard: StencilReactComponent<KsSkeletonCardElement, KsSkeletonCardEvents, KsSkeletonCardSlots> = /*@__PURE__*/ createComponent<KsSkeletonCardElement, KsSkeletonCardEvents, KsSkeletonCardSlots>({
    tagName: 'ks-skeleton-card',
    elementClass: KsSkeletonCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSkeletonCardEvents,
    slots: {} as KsSkeletonCardSlots,
    displayName: 'KsSkeletonCard',
    defineCustomElement: defineKsSkeletonCard,
    tagNameTransform: true
});

export default KsSkeletonCard;
