'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSkeletonAvatar as KsSkeletonAvatarElement, defineCustomElement as defineKsSkeletonAvatar } from "@fe-infra/keystone/dist/components/ks-skeleton-avatar.js";
import React from 'react';

type KsSkeletonAvatarSlots = NonNullable<unknown>;
type KsSkeletonAvatarEvents = NonNullable<unknown>;
export type KsSkeletonAvatarProps = ComponentProps<KsSkeletonAvatarElement, KsSkeletonAvatarEvents, KsSkeletonAvatarSlots>;

const KsSkeletonAvatar: StencilReactComponent<KsSkeletonAvatarElement, KsSkeletonAvatarEvents, KsSkeletonAvatarSlots> = /*@__PURE__*/ createComponent<KsSkeletonAvatarElement, KsSkeletonAvatarEvents, KsSkeletonAvatarSlots>({
    tagName: 'ks-skeleton-avatar',
    elementClass: KsSkeletonAvatarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSkeletonAvatarEvents,
    slots: {} as KsSkeletonAvatarSlots,
    displayName: 'KsSkeletonAvatar',
    defineCustomElement: defineKsSkeletonAvatar,
    tagNameTransform: true
});

export default KsSkeletonAvatar;
