'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSkeletonButton as KsSkeletonButtonElement, defineCustomElement as defineKsSkeletonButton } from "@fe-infra/keystone/dist/components/ks-skeleton-button.js";
import React from 'react';

type KsSkeletonButtonSlots = NonNullable<unknown>;
type KsSkeletonButtonEvents = NonNullable<unknown>;
export type KsSkeletonButtonProps = ComponentProps<KsSkeletonButtonElement, KsSkeletonButtonEvents, KsSkeletonButtonSlots>;

const KsSkeletonButton: StencilReactComponent<KsSkeletonButtonElement, KsSkeletonButtonEvents, KsSkeletonButtonSlots> = /*@__PURE__*/ createComponent<KsSkeletonButtonElement, KsSkeletonButtonEvents, KsSkeletonButtonSlots>({
    tagName: 'ks-skeleton-button',
    elementClass: KsSkeletonButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSkeletonButtonEvents,
    slots: {} as KsSkeletonButtonSlots,
    displayName: 'KsSkeletonButton',
    defineCustomElement: defineKsSkeletonButton,
    tagNameTransform: true
});

export default KsSkeletonButton;
