'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSkeletonTile as KsSkeletonTileElement, defineCustomElement as defineKsSkeletonTile } from "@fe-infra/keystone/dist/components/ks-skeleton-tile.js";
import React from 'react';

type KsSkeletonTileSlots = NonNullable<unknown>;
type KsSkeletonTileEvents = NonNullable<unknown>;
export type KsSkeletonTileProps = ComponentProps<KsSkeletonTileElement, KsSkeletonTileEvents, KsSkeletonTileSlots>;

const KsSkeletonTile: StencilReactComponent<KsSkeletonTileElement, KsSkeletonTileEvents, KsSkeletonTileSlots> = /*@__PURE__*/ createComponent<KsSkeletonTileElement, KsSkeletonTileEvents, KsSkeletonTileSlots>({
    tagName: 'ks-skeleton-tile',
    elementClass: KsSkeletonTileElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSkeletonTileEvents,
    slots: {} as KsSkeletonTileSlots,
    displayName: 'KsSkeletonTile',
    defineCustomElement: defineKsSkeletonTile,
    tagNameTransform: true
});

export default KsSkeletonTile;
