'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSkeletonText as KsSkeletonTextElement, defineCustomElement as defineKsSkeletonText } from "@fe-infra/keystone/dist/components/ks-skeleton-text.js";
import React from 'react';

type KsSkeletonTextSlots = NonNullable<unknown>;
type KsSkeletonTextEvents = NonNullable<unknown>;
export type KsSkeletonTextProps = ComponentProps<KsSkeletonTextElement, KsSkeletonTextEvents, KsSkeletonTextSlots>;

const KsSkeletonText: StencilReactComponent<KsSkeletonTextElement, KsSkeletonTextEvents, KsSkeletonTextSlots> = /*@__PURE__*/ createComponent<KsSkeletonTextElement, KsSkeletonTextEvents, KsSkeletonTextSlots>({
    tagName: 'ks-skeleton-text',
    elementClass: KsSkeletonTextElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSkeletonTextEvents,
    slots: {} as KsSkeletonTextSlots,
    displayName: 'KsSkeletonText',
    defineCustomElement: defineKsSkeletonText,
    tagNameTransform: true
});

export default KsSkeletonText;
