'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSlider as KsSliderElement, defineCustomElement as defineKsSlider } from "@fe-infra/keystone/dist/components/ks-slider.js";
import React from 'react';

type KsSliderSlots = NonNullable<unknown>;
type KsSliderEvents = {
    onChange: EventName<number | number[]>,
    onChangeComplete: EventName<number | number[]>
};
export type KsSliderProps = ComponentProps<KsSliderElement, KsSliderEvents, KsSliderSlots>;

const KsSlider: StencilReactComponent<KsSliderElement, KsSliderEvents, KsSliderSlots> = /*@__PURE__*/ createComponent<KsSliderElement, KsSliderEvents, KsSliderSlots>({
    tagName: 'ks-slider',
    elementClass: KsSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onChangeComplete: 'ksChangeComplete'
    } as KsSliderEvents,
    slots: {} as KsSliderSlots,
    displayName: 'KsSlider',
    defineCustomElement: defineKsSlider,
    tagNameTransform: true
});

export default KsSlider;
