'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSpace as KsSpaceElement, defineCustomElement as defineKsSpace } from "@fe-infra/keystone/dist/components/ks-space.js";
import React from 'react';

type KsSpaceSlots = NonNullable<unknown>;
type KsSpaceEvents = NonNullable<unknown>;
export type KsSpaceProps = ComponentProps<KsSpaceElement, KsSpaceEvents, KsSpaceSlots>;

const KsSpace: StencilReactComponent<KsSpaceElement, KsSpaceEvents, KsSpaceSlots> = /*@__PURE__*/ createComponent<KsSpaceElement, KsSpaceEvents, KsSpaceSlots>({
    tagName: 'ks-space',
    elementClass: KsSpaceElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSpaceEvents,
    slots: {} as KsSpaceSlots,
    displayName: 'KsSpace',
    defineCustomElement: defineKsSpace,
    tagNameTransform: true
});

export default KsSpace;
