'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSpinner as KsSpinnerElement, defineCustomElement as defineKsSpinner } from "@fe-infra/keystone/dist/components/ks-spinner.js";
import React from 'react';

type KsSpinnerSlots = NonNullable<unknown>;
type KsSpinnerEvents = NonNullable<unknown>;
export type KsSpinnerProps = ComponentProps<KsSpinnerElement, KsSpinnerEvents, KsSpinnerSlots>;

const KsSpinner: StencilReactComponent<KsSpinnerElement, KsSpinnerEvents, KsSpinnerSlots> = /*@__PURE__*/ createComponent<KsSpinnerElement, KsSpinnerEvents, KsSpinnerSlots>({
    tagName: 'ks-spinner',
    elementClass: KsSpinnerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsSpinnerEvents,
    slots: {} as KsSpinnerSlots,
    displayName: 'KsSpinner',
    defineCustomElement: defineKsSpinner,
    tagNameTransform: true
});

export default KsSpinner;
