'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsStatusIcon as KsStatusIconElement, defineCustomElement as defineKsStatusIcon } from "@fe-infra/keystone/dist/components/ks-status-icon.js";
import React from 'react';

type KsStatusIconSlots = NonNullable<unknown>;
type KsStatusIconEvents = NonNullable<unknown>;
export type KsStatusIconProps = ComponentProps<KsStatusIconElement, KsStatusIconEvents, KsStatusIconSlots>;

const KsStatusIcon: StencilReactComponent<KsStatusIconElement, KsStatusIconEvents, KsStatusIconSlots> = /*@__PURE__*/ createComponent<KsStatusIconElement, KsStatusIconEvents, KsStatusIconSlots>({
    tagName: 'ks-status-icon',
    elementClass: KsStatusIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsStatusIconEvents,
    slots: {} as KsStatusIconSlots,
    displayName: 'KsStatusIcon',
    defineCustomElement: defineKsStatusIcon,
    tagNameTransform: true
});

export default KsStatusIcon;
