'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsStatusMessage as KsStatusMessageElement, defineCustomElement as defineKsStatusMessage } from "@fe-infra/keystone/dist/components/ks-status-message.js";
import React from 'react';

type KsStatusMessageSlots = NonNullable<unknown>;
type KsStatusMessageEvents = NonNullable<unknown>;
export type KsStatusMessageProps = ComponentProps<KsStatusMessageElement, KsStatusMessageEvents, KsStatusMessageSlots>;

const KsStatusMessage: StencilReactComponent<KsStatusMessageElement, KsStatusMessageEvents, KsStatusMessageSlots> = /*@__PURE__*/ createComponent<KsStatusMessageElement, KsStatusMessageEvents, KsStatusMessageSlots>({
    tagName: 'ks-status-message',
    elementClass: KsStatusMessageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsStatusMessageEvents,
    slots: {} as KsStatusMessageSlots,
    displayName: 'KsStatusMessage',
    defineCustomElement: defineKsStatusMessage,
    tagNameTransform: true
});

export default KsStatusMessage;
