'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsStep as KsStepElement, defineCustomElement as defineKsStep } from "@fe-infra/keystone/dist/components/ks-step.js";
import React from 'react';

type KsStepSlots = {
    /**
     * Slot for the step's icon.
     */
    icon: string,
    /**
     * Slot for the step's label.
     */
    label: string
};
type KsStepEvents = NonNullable<unknown>;
export type KsStepProps = ComponentProps<KsStepElement, KsStepEvents, KsStepSlots>;

const KsStep: StencilReactComponent<KsStepElement, KsStepEvents, KsStepSlots> = /*@__PURE__*/ createComponent<KsStepElement, KsStepEvents, KsStepSlots>({
    tagName: 'ks-step',
    elementClass: KsStepElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsStepEvents,
    slots: {
        icon: 'icon',
        label: 'label'
    } as KsStepSlots,
    displayName: 'KsStep',
    defineCustomElement: defineKsStep,
    tagNameTransform: true
});

export default KsStep;
