'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsStatusIndicator as KsStatusIndicatorElement, defineCustomElement as defineKsStatusIndicator } from "@fe-infra/keystone/dist/components/ks-status-indicator.js";
import React from 'react';

type KsStatusIndicatorSlots = NonNullable<unknown>;
type KsStatusIndicatorEvents = NonNullable<unknown>;
export type KsStatusIndicatorProps = ComponentProps<KsStatusIndicatorElement, KsStatusIndicatorEvents, KsStatusIndicatorSlots>;

const KsStatusIndicator: StencilReactComponent<KsStatusIndicatorElement, KsStatusIndicatorEvents, KsStatusIndicatorSlots> = /*@__PURE__*/ createComponent<KsStatusIndicatorElement, KsStatusIndicatorEvents, KsStatusIndicatorSlots>({
    tagName: 'ks-status-indicator',
    elementClass: KsStatusIndicatorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsStatusIndicatorEvents,
    slots: {} as KsStatusIndicatorSlots,
    displayName: 'KsStatusIndicator',
    defineCustomElement: defineKsStatusIndicator,
    tagNameTransform: true
});

export default KsStatusIndicator;
