'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsStepper as KsStepperElement, defineCustomElement as defineKsStepper } from "@fe-infra/keystone/dist/components/ks-stepper.js";
import React from 'react';

type KsStepperSlots = NonNullable<unknown>;
type KsStepperEvents = NonNullable<unknown>;
export type KsStepperProps = ComponentProps<KsStepperElement, KsStepperEvents, KsStepperSlots>;

const KsStepper: StencilReactComponent<KsStepperElement, KsStepperEvents, KsStepperSlots> = /*@__PURE__*/ createComponent<KsStepperElement, KsStepperEvents, KsStepperSlots>({
    tagName: 'ks-stepper',
    elementClass: KsStepperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsStepperEvents,
    slots: {} as KsStepperSlots,
    displayName: 'KsStepper',
    defineCustomElement: defineKsStepper,
    tagNameTransform: true
});

export default KsStepper;
