'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSubMenu as KsSubMenuElement, defineCustomElement as defineKsSubMenu } from "@fe-infra/keystone/dist/components/ks-sub-menu.js";
import React from 'react';

type KsSubMenuSlots = {
    /**
     * Slot for content to be placed before the sub-menu title, typically an icon.
     */
    prefix: string,
    /**
     * Slot for the main text content of the sub-menu title.
     */
    title: string,
    /**
     * Slot for content to be placed after the sub-menu title.
     */
    suffix: string
};
type KsSubMenuEvents = { onChange: EventName<boolean> };
export type KsSubMenuProps = ComponentProps<KsSubMenuElement, KsSubMenuEvents, KsSubMenuSlots>;

const KsSubMenu: StencilReactComponent<KsSubMenuElement, KsSubMenuEvents, KsSubMenuSlots> = /*@__PURE__*/ createComponent<KsSubMenuElement, KsSubMenuEvents, KsSubMenuSlots>({
    tagName: 'ks-sub-menu',
    elementClass: KsSubMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsSubMenuEvents,
    slots: {
        prefix: 'prefix',
        title: 'title',
        suffix: 'suffix'
    } as KsSubMenuSlots,
    displayName: 'KsSubMenu',
    defineCustomElement: defineKsSubMenu,
    tagNameTransform: true
});

export default KsSubMenu;
