'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsSwitch as KsSwitchElement, defineCustomElement as defineKsSwitch } from "@fe-infra/keystone/dist/components/ks-switch.js";
import React from 'react';

type KsSwitchSlots = {
    /**
     * Slot for the description text of the switch.
     */
    description: string,
    /**
     * The title slot for the switch label.
     */
    title: string
};
type KsSwitchEvents = { onChange: EventName<boolean> };
export type KsSwitchProps = ComponentProps<KsSwitchElement, KsSwitchEvents, KsSwitchSlots>;

const KsSwitch: StencilReactComponent<KsSwitchElement, KsSwitchEvents, KsSwitchSlots> = /*@__PURE__*/ createComponent<KsSwitchElement, KsSwitchEvents, KsSwitchSlots>({
    tagName: 'ks-switch',
    elementClass: KsSwitchElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsSwitchEvents,
    slots: {
        description: 'description',
        title: 'title'
    } as KsSwitchSlots,
    displayName: 'KsSwitch',
    defineCustomElement: defineKsSwitch,
    tagNameTransform: true
});

export default KsSwitch;
