'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTabsItem as KsTabsItemElement, defineCustomElement as defineKsTabsItem } from "@fe-infra/keystone/dist/components/ks-tabs-item.js";
import React from 'react';

type KsTabsItemSlots = {
    /**
     * Content for the tab's header/label. This content will be displayed in the tab bar by the parent `ks-tabs` component.
     */
    header: string
};
type KsTabsItemEvents = NonNullable<unknown>;
export type KsTabsItemProps = ComponentProps<KsTabsItemElement, KsTabsItemEvents, KsTabsItemSlots>;

const KsTabsItem: StencilReactComponent<KsTabsItemElement, KsTabsItemEvents, KsTabsItemSlots> = /*@__PURE__*/ createComponent<KsTabsItemElement, KsTabsItemEvents, KsTabsItemSlots>({
    tagName: 'ks-tabs-item',
    elementClass: KsTabsItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsTabsItemEvents,
    slots: { header: 'header' } as KsTabsItemSlots,
    displayName: 'KsTabsItem',
    defineCustomElement: defineKsTabsItem,
    tagNameTransform: true
});

export default KsTabsItem;
