'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IKsTableColumn } from "@fe-infra/keystone";
import { KsTable as KsTableElement, defineCustomElement as defineKsTable } from "@fe-infra/keystone/dist/components/ks-table.js";
import React from 'react';

type KsTableSlots = {
    /**
     * Content to display when the table has no data.
     */
    empty: string
};
type KsTableEvents = {
    onRowSelect: EventName<(string | number)[]>,
    onRowHover: EventName<number | null>,
    onRowClick: EventName<object>,
    onDataViewChange: EventName<{
        columns: IKsTableColumn[];
        sortOrders: { key: string; sortOrder: IKsTableColumn['sortOrder'] }[];
        triggeredBy: 'sortOrder';
    }>,
    onSorterClick: EventName<{
        id: unknown;
        direction: false | 'descend' | 'ascend';
    }>
};
export type KsTableProps = ComponentProps<KsTableElement, KsTableEvents, KsTableSlots>;

const KsTable: StencilReactComponent<KsTableElement, KsTableEvents, KsTableSlots> = /*@__PURE__*/ createComponent<KsTableElement, KsTableEvents, KsTableSlots>({
    tagName: 'ks-table',
    elementClass: KsTableElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onRowSelect: 'ksRowSelect',
        onRowHover: 'ksRowHover',
        onRowClick: 'ksRowClick',
        onDataViewChange: 'ksDataViewChange',
        onSorterClick: 'ksSorterClick'
    } as KsTableEvents,
    slots: { empty: 'empty' } as KsTableSlots,
    displayName: 'KsTable',
    defineCustomElement: defineKsTable,
    tagNameTransform: true
});

export default KsTable;
