'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTag as KsTagElement, defineCustomElement as defineKsTag } from "@fe-infra/keystone/dist/components/ks-tag.js";
import React from 'react';

type KsTagSlots = {
    /**
     * Slot for the icon.
     */
    icon: string
};
type KsTagEvents = {
    onClose: EventName<any>,
    onStartDrag: EventName<any>
};
export type KsTagProps = ComponentProps<KsTagElement, KsTagEvents, KsTagSlots>;

const KsTag: StencilReactComponent<KsTagElement, KsTagEvents, KsTagSlots> = /*@__PURE__*/ createComponent<KsTagElement, KsTagEvents, KsTagSlots>({
    tagName: 'ks-tag',
    elementClass: KsTagElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClose: 'ksClose',
        onStartDrag: 'ksStartDrag'
    } as KsTagEvents,
    slots: { icon: 'icon' } as KsTagSlots,
    displayName: 'KsTag',
    defineCustomElement: defineKsTag,
    tagNameTransform: true
});

export default KsTag;
