'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTabs as KsTabsElement, defineCustomElement as defineKsTabs } from "@fe-infra/keystone/dist/components/ks-tabs.js";
import React from 'react';

type KsTabsSlots = {
    /**
     * Slot for extra content to be displayed on the right side of the tab bar.
     */
    extra: string
};
type KsTabsEvents = { onTabClick: EventName<string> };
export type KsTabsProps = ComponentProps<KsTabsElement, KsTabsEvents, KsTabsSlots>;

const KsTabs: StencilReactComponent<KsTabsElement, KsTabsEvents, KsTabsSlots> = /*@__PURE__*/ createComponent<KsTabsElement, KsTabsEvents, KsTabsSlots>({
    tagName: 'ks-tabs',
    elementClass: KsTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onTabClick: 'ksTabClick' } as KsTabsEvents,
    slots: { extra: 'extra' } as KsTabsSlots,
    displayName: 'KsTabs',
    defineCustomElement: defineKsTabs,
    tagNameTransform: true
});

export default KsTabs;
