'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsText as KsTextElement, defineCustomElement as defineKsText } from "@fe-infra/keystone/dist/components/ks-text.js";
import React from 'react';

type KsTextSlots = {
    /**
     * Slot for content to be displayed inside the definition hint tooltip.
     */
    definition: string
};
type KsTextEvents = NonNullable<unknown>;
export type KsTextProps = ComponentProps<KsTextElement, KsTextEvents, KsTextSlots>;

const KsText: StencilReactComponent<KsTextElement, KsTextEvents, KsTextSlots> = /*@__PURE__*/ createComponent<KsTextElement, KsTextEvents, KsTextSlots>({
    tagName: 'ks-text',
    elementClass: KsTextElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsTextEvents,
    slots: { definition: 'definition' } as KsTextSlots,
    displayName: 'KsText',
    defineCustomElement: defineKsText,
    tagNameTransform: true
});

export default KsText;
