'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTextField as KsTextFieldElement, defineCustomElement as defineKsTextField } from "@fe-infra/keystone/dist/components/ks-text-field.js";
import React from 'react';

type KsTextFieldSlots = {
    /**
     * Slot for content to be displayed before the input field.
     */
    prefix: string,
    /**
     * Slot for content to be displayed after the input field.
     */
    suffix: string
};
type KsTextFieldEvents = {
    onChange: EventName<string>,
    onClick: EventName<MouseEvent>,
    onFocus: EventName<FocusEvent>,
    onBlur: EventName<FocusEvent>,
    onKeydownEnter: EventName<KeyboardEvent>
};
export type KsTextFieldProps = ComponentProps<KsTextFieldElement, KsTextFieldEvents, KsTextFieldSlots>;

const KsTextField: StencilReactComponent<KsTextFieldElement, KsTextFieldEvents, KsTextFieldSlots> = /*@__PURE__*/ createComponent<KsTextFieldElement, KsTextFieldEvents, KsTextFieldSlots>({
    tagName: 'ks-text-field',
    elementClass: KsTextFieldElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onClick: 'ksClick',
        onFocus: 'ksFocus',
        onBlur: 'ksBlur',
        onKeydownEnter: 'ksKeydownEnter'
    } as KsTextFieldEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix'
    } as KsTextFieldSlots,
    displayName: 'KsTextField',
    defineCustomElement: defineKsTextField,
    tagNameTransform: true
});

export default KsTextField;
