'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsThumbnail as KsThumbnailElement, defineCustomElement as defineKsThumbnail } from "@fe-infra/keystone/dist/components/ks-thumbnail.js";
import React from 'react';

type KsThumbnailSlots = {
    /**
     * The slot for displaying a custom icon within the thumbnail. Rendered only if the `block` prop is false and the slot is provided.
     */
    icon: string
};
type KsThumbnailEvents = {
    onPlay: EventName<void>,
    onPause: EventName<void>,
    onAction: EventName<string | number>
};
export type KsThumbnailProps = ComponentProps<KsThumbnailElement, KsThumbnailEvents, KsThumbnailSlots>;

const KsThumbnail: StencilReactComponent<KsThumbnailElement, KsThumbnailEvents, KsThumbnailSlots> = /*@__PURE__*/ createComponent<KsThumbnailElement, KsThumbnailEvents, KsThumbnailSlots>({
    tagName: 'ks-thumbnail',
    elementClass: KsThumbnailElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onPlay: 'ksPlay',
        onPause: 'ksPause',
        onAction: 'ksAction'
    } as KsThumbnailEvents,
    slots: { icon: 'icon' } as KsThumbnailSlots,
    displayName: 'KsThumbnail',
    defineCustomElement: defineKsThumbnail,
    tagNameTransform: true
});

export default KsThumbnail;
