'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTile as KsTileElement, defineCustomElement as defineKsTile } from "@fe-infra/keystone/dist/components/ks-tile.js";
import React from 'react';

type KsTileSlots = {
    /**
     * The slot for the title.
     */
    title: string,
    /**
     * The slot for the extra content, which is displayed prominently at the top.
     */
    extra: string,
    /**
     * The slot for the top icon area.
     */
    icon: string,
    /**
     * The slot for the footer content.
     */
    footer: string
};
type KsTileEvents = { onChange: EventName<boolean> };
export type KsTileProps = ComponentProps<KsTileElement, KsTileEvents, KsTileSlots>;

const KsTile: StencilReactComponent<KsTileElement, KsTileEvents, KsTileSlots> = /*@__PURE__*/ createComponent<KsTileElement, KsTileEvents, KsTileSlots>({
    tagName: 'ks-tile',
    elementClass: KsTileElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsTileEvents,
    slots: {
        title: 'title',
        extra: 'extra',
        icon: 'icon',
        footer: 'footer'
    } as KsTileSlots,
    displayName: 'KsTile',
    defineCustomElement: defineKsTile,
    tagNameTransform: true
});

export default KsTile;
