'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTimePicker as KsTimePickerElement, defineCustomElement as defineKsTimePicker } from "@fe-infra/keystone/dist/components/ks-time-picker.js";
import React from 'react';

type KsTimePickerSlots = {
    /**
     * Slot for custom prefix content.
     */
    prefix: string,
    /**
     * Slot for custom suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset time options, displayed in the picker panel.
     */
    preset: string
};
type KsTimePickerEvents = { onChange: EventName<string | string[]> };
export type KsTimePickerProps = ComponentProps<KsTimePickerElement, KsTimePickerEvents, KsTimePickerSlots>;

const KsTimePicker: StencilReactComponent<KsTimePickerElement, KsTimePickerEvents, KsTimePickerSlots> = /*@__PURE__*/ createComponent<KsTimePickerElement, KsTimePickerEvents, KsTimePickerSlots>({
    tagName: 'ks-time-picker',
    elementClass: KsTimePickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsTimePickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsTimePickerSlots,
    displayName: 'KsTimePicker',
    defineCustomElement: defineKsTimePicker,
    tagNameTransform: true
});

export default KsTimePicker;
