'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTileMetric as KsTileMetricElement, defineCustomElement as defineKsTileMetric } from "@fe-infra/keystone/dist/components/ks-tile-metric.js";
import React from 'react';

type KsTileMetricSlots = {
    /**
     * The slot for the title.
     */
    title: string,
    /**
     * Slot for an icon, typically displayed at the top or alongside the action element.
     */
    icon: string,
    /**
     * Slot for extra content, usually displayed in the header area of the tile.
     */
    extra: string
};
type KsTileMetricEvents = { onChange: EventName<boolean> };
export type KsTileMetricProps = ComponentProps<KsTileMetricElement, KsTileMetricEvents, KsTileMetricSlots>;

const KsTileMetric: StencilReactComponent<KsTileMetricElement, KsTileMetricEvents, KsTileMetricSlots> = /*@__PURE__*/ createComponent<KsTileMetricElement, KsTileMetricEvents, KsTileMetricSlots>({
    tagName: 'ks-tile-metric',
    elementClass: KsTileMetricElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChange: 'ksChange' } as KsTileMetricEvents,
    slots: {
        title: 'title',
        icon: 'icon',
        extra: 'extra'
    } as KsTileMetricSlots,
    displayName: 'KsTileMetric',
    defineCustomElement: defineKsTileMetric,
    tagNameTransform: true
});

export default KsTileMetric;
