'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTimeline as KsTimelineElement, defineCustomElement as defineKsTimeline } from "@fe-infra/keystone/dist/components/ks-timeline.js";
import React from 'react';

type KsTimelineSlots = NonNullable<unknown>;
type KsTimelineEvents = NonNullable<unknown>;
export type KsTimelineProps = ComponentProps<KsTimelineElement, KsTimelineEvents, KsTimelineSlots>;

const KsTimeline: StencilReactComponent<KsTimelineElement, KsTimelineEvents, KsTimelineSlots> = /*@__PURE__*/ createComponent<KsTimelineElement, KsTimelineEvents, KsTimelineSlots>({
    tagName: 'ks-timeline',
    elementClass: KsTimelineElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsTimelineEvents,
    slots: {} as KsTimelineSlots,
    displayName: 'KsTimeline',
    defineCustomElement: defineKsTimeline,
    tagNameTransform: true
});

export default KsTimeline;
