'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsToast as KsToastElement, defineCustomElement as defineKsToast } from "@fe-infra/keystone/dist/components/ks-toast.js";
import React from 'react';

type KsToastSlots = {
    /**
     * Slot for the icon displayed in the toast body.
     */
    icon: string,
    /**
     * Slot for the entire body of the toast, which includes the icon and main content.
     */
    body: string,
    /**
     * Slot for action elements, displayed at the end of the toast.
     */
    action: string,
    /**
     * Slot for the content of the close button.
     */
    closebtn: string
};
type KsToastEvents = { onClose: EventName<any> };
export type KsToastProps = ComponentProps<KsToastElement, KsToastEvents, KsToastSlots>;

const KsToast: StencilReactComponent<KsToastElement, KsToastEvents, KsToastSlots> = /*@__PURE__*/ createComponent<KsToastElement, KsToastEvents, KsToastSlots>({
    tagName: 'ks-toast',
    elementClass: KsToastElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onClose: 'ksClose' } as KsToastEvents,
    slots: {
        icon: 'icon',
        body: 'body',
        action: 'action',
        closebtn: 'closebtn'
    } as KsToastSlots,
    displayName: 'KsToast',
    defineCustomElement: defineKsToast,
    tagNameTransform: true
});

export default KsToast;
