'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTooltip as KsTooltipElement, defineCustomElement as defineKsTooltip } from "@fe-infra/keystone/dist/components/ks-tooltip.js";
import React from 'react';

type KsTooltipSlots = {
    /**
     * popper body
     */
    body: string,
    /**
     * popover content
     */
    content: string
};
type KsTooltipEvents = {
    onOutClick: EventName<void>,
    onVisibleChange: EventName<boolean>,
    onAfterOpen: EventName<void>,
    onAfterClose: EventName<void>
};
export type KsTooltipProps = ComponentProps<KsTooltipElement, KsTooltipEvents, KsTooltipSlots>;

const KsTooltip: StencilReactComponent<KsTooltipElement, KsTooltipEvents, KsTooltipSlots> = /*@__PURE__*/ createComponent<KsTooltipElement, KsTooltipEvents, KsTooltipSlots>({
    tagName: 'ks-tooltip',
    elementClass: KsTooltipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onOutClick: 'ksOutClick',
        onVisibleChange: 'ksVisibleChange',
        onAfterOpen: 'ksAfterOpen',
        onAfterClose: 'ksAfterClose'
    } as KsTooltipEvents,
    slots: {
        body: 'body',
        content: 'content'
    } as KsTooltipSlots,
    displayName: 'KsTooltip',
    defineCustomElement: defineKsTooltip,
    tagNameTransform: true
});

export default KsTooltip;
