'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsToastBox as KsToastBoxElement, defineCustomElement as defineKsToastBox } from "@fe-infra/keystone/dist/components/ks-toast-box.js";
import React from 'react';

type KsToastBoxSlots = NonNullable<unknown>;
type KsToastBoxEvents = NonNullable<unknown>;
export type KsToastBoxProps = ComponentProps<KsToastBoxElement, KsToastBoxEvents, KsToastBoxSlots>;

const KsToastBox: StencilReactComponent<KsToastBoxElement, KsToastBoxEvents, KsToastBoxSlots> = /*@__PURE__*/ createComponent<KsToastBoxElement, KsToastBoxEvents, KsToastBoxSlots>({
    tagName: 'ks-toast-box',
    elementClass: KsToastBoxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KsToastBoxEvents,
    slots: {} as KsToastBoxSlots,
    displayName: 'KsToastBox',
    defineCustomElement: defineKsToastBox,
    tagNameTransform: true
});

export default KsToastBox;
