'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { KsTransition as KsTransitionElement, defineCustomElement as defineKsTransition } from "@fe-infra/keystone/dist/components/ks-transition.js";
import React from 'react';

type KsTransitionSlots = NonNullable<unknown>;
type KsTransitionEvents = {
    onEnter: EventName<HTMLElement>,
    onEntering: EventName<HTMLElement>,
    onEntered: EventName<HTMLElement>,
    onExit: EventName<HTMLElement>,
    onExiting: EventName<HTMLElement>,
    onExited: EventName<HTMLElement>
};
export type KsTransitionProps = ComponentProps<KsTransitionElement, KsTransitionEvents, KsTransitionSlots>;

const KsTransition: StencilReactComponent<KsTransitionElement, KsTransitionEvents, KsTransitionSlots> = /*@__PURE__*/ createComponent<KsTransitionElement, KsTransitionEvents, KsTransitionSlots>({
    tagName: 'ks-transition',
    elementClass: KsTransitionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onEnter: 'ksEnter',
        onEntering: 'ksEntering',
        onEntered: 'ksEntered',
        onExit: 'ksExit',
        onExiting: 'ksExiting',
        onExited: 'ksExited'
    } as KsTransitionEvents,
    slots: {} as KsTransitionSlots,
    displayName: 'KsTransition',
    defineCustomElement: defineKsTransition,
    tagNameTransform: true
});

export default KsTransition;
