'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type TreeDataNode, type TreeViewCheckParams, type TreeViewToggleExpandParams } from "@fe-infra/keystone";
import { KsTreeView as KsTreeViewElement, defineCustomElement as defineKsTreeView } from "@fe-infra/keystone/dist/components/ks-tree-view.js";
import React from 'react';

type KsTreeViewSlots = NonNullable<unknown>;
type KsTreeViewEvents = {
    onCheck: EventName<TreeViewCheckParams>,
    onCheckFull: EventName<TreeDataNode['key'][]>,
    onLoadMore: EventName<TreeDataNode['key']>,
    onToggleExpand: EventName<TreeViewToggleExpandParams>
};
export type KsTreeViewProps = ComponentProps<KsTreeViewElement, KsTreeViewEvents, KsTreeViewSlots>;

const KsTreeView: StencilReactComponent<KsTreeViewElement, KsTreeViewEvents, KsTreeViewSlots> = /*@__PURE__*/ createComponent<KsTreeViewElement, KsTreeViewEvents, KsTreeViewSlots>({
    tagName: 'ks-tree-view',
    elementClass: KsTreeViewElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onCheck: 'ksCheck',
        onCheckFull: 'ksCheckFull',
        onLoadMore: 'ksLoadMore',
        onToggleExpand: 'ksToggleExpand'
    } as KsTreeViewEvents,
    slots: {} as KsTreeViewSlots,
    displayName: 'KsTreeView',
    defineCustomElement: defineKsTreeView,
    tagNameTransform: true
});

export default KsTreeView;
