'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type UploadChangeParam, type UploadFile } from "@fe-infra/keystone";
import { KsUploadDrop as KsUploadDropElement, defineCustomElement as defineKsUploadDrop } from "@fe-infra/keystone/dist/components/ks-upload-drop.js";
import React from 'react';

type KsUploadDropSlots = NonNullable<unknown>;
type KsUploadDropEvents = {
    onChange: EventName<UploadChangeParam<UploadFile>>,
    onError: EventName<UploadChangeParam<UploadFile>>
};
export type KsUploadDropProps = ComponentProps<KsUploadDropElement, KsUploadDropEvents, KsUploadDropSlots>;

const KsUploadDrop: StencilReactComponent<KsUploadDropElement, KsUploadDropEvents, KsUploadDropSlots> = /*@__PURE__*/ createComponent<KsUploadDropElement, KsUploadDropEvents, KsUploadDropSlots>({
    tagName: 'ks-upload-drop',
    elementClass: KsUploadDropElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onError: 'ksError'
    } as KsUploadDropEvents,
    slots: {} as KsUploadDropSlots,
    displayName: 'KsUploadDrop',
    defineCustomElement: defineKsUploadDrop,
    tagNameTransform: true
});

export default KsUploadDrop;
