'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type UploadChangeParam, type UploadFile } from "@fe-infra/keystone";
import { KsUpload as KsUploadElement, defineCustomElement as defineKsUpload } from "@fe-infra/keystone/dist/components/ks-upload.js";
import React from 'react';

type KsUploadSlots = NonNullable<unknown>;
type KsUploadEvents = {
    onChange: EventName<UploadChangeParam<UploadFile>>,
    onError: EventName<UploadChangeParam<UploadFile>>,
    onExceededMaxChange: EventName<boolean>
};
export type KsUploadProps = ComponentProps<KsUploadElement, KsUploadEvents, KsUploadSlots>;

const KsUpload: StencilReactComponent<KsUploadElement, KsUploadEvents, KsUploadSlots> = /*@__PURE__*/ createComponent<KsUploadElement, KsUploadEvents, KsUploadSlots>({
    tagName: 'ks-upload',
    elementClass: KsUploadElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onError: 'ksError',
        onExceededMaxChange: 'exceededMaxChange'
    } as KsUploadEvents,
    slots: {} as KsUploadSlots,
    displayName: 'KsUpload',
    defineCustomElement: defineKsUpload,
    tagNameTransform: true
});

export default KsUpload;
