'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type UploadChangeParam, type UploadFile } from "@fe-infra/keystone";
import { KsUploadAvatar as KsUploadAvatarElement, defineCustomElement as defineKsUploadAvatar } from "@fe-infra/keystone/dist/components/ks-upload-avatar.js";
import React from 'react';

type KsUploadAvatarSlots = NonNullable<unknown>;
type KsUploadAvatarEvents = {
    onChange: EventName<UploadChangeParam<UploadFile>>,
    onError: EventName<UploadChangeParam<UploadFile>>
};
export type KsUploadAvatarProps = ComponentProps<KsUploadAvatarElement, KsUploadAvatarEvents, KsUploadAvatarSlots>;

const KsUploadAvatar: StencilReactComponent<KsUploadAvatarElement, KsUploadAvatarEvents, KsUploadAvatarSlots> = /*@__PURE__*/ createComponent<KsUploadAvatarElement, KsUploadAvatarEvents, KsUploadAvatarSlots>({
    tagName: 'ks-upload-avatar',
    elementClass: KsUploadAvatarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onError: 'ksError'
    } as KsUploadAvatarEvents,
    slots: {} as KsUploadAvatarSlots,
    displayName: 'KsUploadAvatar',
    defineCustomElement: defineKsUploadAvatar,
    tagNameTransform: true
});

export default KsUploadAvatar;
