'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsWeekPicker as KsWeekPickerElement, defineCustomElement as defineKsWeekPicker } from "@fe-infra/keystone/dist/components/ks-week-picker.js";
import React from 'react';

type KsWeekPickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset week options.
     */
    preset: string
};
type KsWeekPickerEvents = {
    onChange: EventName<IDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsWeekPickerProps = ComponentProps<KsWeekPickerElement, KsWeekPickerEvents, KsWeekPickerSlots>;

const KsWeekPicker: StencilReactComponent<KsWeekPickerElement, KsWeekPickerEvents, KsWeekPickerSlots> = /*@__PURE__*/ createComponent<KsWeekPickerElement, KsWeekPickerEvents, KsWeekPickerSlots>({
    tagName: 'ks-week-picker',
    elementClass: KsWeekPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsWeekPickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsWeekPickerSlots,
    displayName: 'KsWeekPicker',
    defineCustomElement: defineKsWeekPicker,
    tagNameTransform: true
});

export default KsWeekPicker;
