'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { ComponentProps, EventName, StencilReactComponent } from '@byted-keystone/react-output-target/runtime';
import { createComponent } from '@byted-keystone/react-output-target/runtime';
import { type IDateValue } from "@fe-infra/keystone";
import { KsYearPicker as KsYearPickerElement, defineCustomElement as defineKsYearPicker } from "@fe-infra/keystone/dist/components/ks-year-picker.js";
import React from 'react';

type KsYearPickerSlots = {
    /**
     * Slot for prefix content.
     */
    prefix: string,
    /**
     * Slot for suffix content.
     */
    suffix: string,
    /**
     * Slot for the expand indicator icon.
     */
    showIcon: string,
    /**
     * Slot for the clear icon.
     */
    closeIcon: string,
    /**
     * Slot for preset year options.
     */
    preset: string
};
type KsYearPickerEvents = {
    onChange: EventName<IDateValue>,
    onShow: EventName<void>,
    onHide: EventName<void>,
    onVisibleChange: EventName<boolean>
};
export type KsYearPickerProps = ComponentProps<KsYearPickerElement, KsYearPickerEvents, KsYearPickerSlots>;

const KsYearPicker: StencilReactComponent<KsYearPickerElement, KsYearPickerEvents, KsYearPickerSlots> = /*@__PURE__*/ createComponent<KsYearPickerElement, KsYearPickerEvents, KsYearPickerSlots>({
    tagName: 'ks-year-picker',
    elementClass: KsYearPickerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChange: 'ksChange',
        onShow: 'ksShow',
        onHide: 'ksHide',
        onVisibleChange: 'ksVisibleChange'
    } as KsYearPickerEvents,
    slots: {
        prefix: 'prefix',
        suffix: 'suffix',
        showIcon: 'show-icon',
        closeIcon: 'close-icon',
        preset: 'preset'
    } as KsYearPickerSlots,
    displayName: 'KsYearPicker',
    defineCustomElement: defineKsYearPicker,
    tagNameTransform: true
});

export default KsYearPicker;
